/* Generated by scripts/generate.py. Do not edit. */
static void exercise_public_calls(pilot_client *client)
{
    pilot_error error;
    {
        pilot_battery_request_result out = {0};
        assert(pilot_battery_request(client, "sample", &out, &error) == PILOT_OK);
        assert(!strcmp(out.response, "sample"));
        pilot_battery_request_clear(&out);
        pilot_battery_request_clear(&out);
    }
    {
        pilot_connection_get_active_result out = {0};
        assert(pilot_connection_get_active(client, &out, &error) == PILOT_OK);
        assert(out.index == -23);
        pilot_connection_get_active_clear(&out);
        pilot_connection_get_active_clear(&out);
    }
    {
        pilot_connection_get_relay_result out = {0};
        assert(pilot_connection_get_relay(client, &out, &error) == PILOT_OK);
        assert(!strcmp(out.type, "sample"));
        assert(out.connected == true);
        assert(!strcmp(out.ip, "sample"));
        assert(out.port == 1234);
        assert(out.subscribe_count == -23);
        assert(out.is_active == true);
        pilot_connection_get_relay_clear(&out);
        pilot_connection_get_relay_clear(&out);
    }
    {
        pilot_connection_get_p2p_result out = {0};
        assert(pilot_connection_get_p2p(client, &out, &error) == PILOT_OK);
        assert(!strcmp(out.type, "sample"));
        assert(out.connected == true);
        assert(!strcmp(out.ip, "sample"));
        assert(out.port == 1234);
        assert(out.subscribe_count == -23);
        assert(out.is_active == true);
        pilot_connection_get_p2p_clear(&out);
        pilot_connection_get_p2p_clear(&out);
    }
    {
        pilot_connection_get_status_result out = {0};
        assert(pilot_connection_get_status(client, &out, &error) == PILOT_OK);
        assert(out.endpoints_count == 2 && out.endpoints);
        assert(!strcmp(out.endpoints[0].type, "sample"));
        assert(out.endpoints[0].connected == true);
        assert(!strcmp(out.endpoints[0].ip, "sample"));
        assert(out.endpoints[0].port == 1234);
        assert(out.endpoints[0].subscribe_count == -23);
        assert(out.endpoints[0].is_active == true);
        assert(out.active_index == -23);
        pilot_connection_get_status_clear(&out);
        pilot_connection_get_status_clear(&out);
    }
    {
        pilot_control_read_result out = {0};
        assert(pilot_control_read(client, &out, &error) == PILOT_OK);
        assert(out.signals_count == 2 && out.signals);
        assert(out.signals[0] == -23);
        assert(out.last_rx_ms == -9007199254740999LL);
        pilot_control_read_clear(&out);
        pilot_control_read_clear(&out);
    }
    {
        pilot_control_set_result out = {0};
        assert(pilot_control_set(client, -23, -23, &out, &error) == PILOT_OK);
        assert(out.applied == true);
        pilot_control_set_clear(&out);
        pilot_control_set_clear(&out);
    }
    {
        pilot_imu_read_result out = {0};
        assert(pilot_imu_read(client, &out, &error) == PILOT_OK);
        assert(out.last_sample_ms == -9007199254740999LL);
        assert(out.valid == true);
        assert(out.gyro_x == 1.25);
        assert(out.gyro_y == 1.25);
        assert(out.gyro_z == 1.25);
        assert(out.accel_x == 1.25);
        assert(out.accel_y == 1.25);
        assert(out.accel_z == 1.25);
        pilot_imu_read_clear(&out);
        pilot_imu_read_clear(&out);
    }
    {
        pilot_device_read_result out = {0};
        assert(pilot_device_read(client, &out, &error) == PILOT_OK);
        assert(out.last_update_ms == -9007199254740999LL);
        assert(out.has_imu == true);
        assert(out.gyro_x == 1.25);
        assert(out.gyro_y == 1.25);
        assert(out.gyro_z == 1.25);
        assert(out.accel_x == 1.25);
        assert(out.accel_y == 1.25);
        assert(out.accel_z == 1.25);
        assert(out.temperature == 1.25);
        assert(out.memory_usage == 1.25);
        assert(out.cpu_usage == 1.25);
        assert(out.disk_usage == 1.25);
        assert(out.battery_percent == -23);
        assert(out.voltage == 1.25);
        assert(out.rssi_dbm == -23);
        assert(out.has_gps == true);
        assert(out.latitude == 1.25);
        assert(out.longitude == 1.25);
        assert(out.altitude == 1.25);
        assert(out.gps_satellites == -23);
        assert(out.hdop == 1.25);
        pilot_device_read_clear(&out);
        pilot_device_read_clear(&out);
    }
    {
        pilot_magnetometer_read_result out = {0};
        assert(pilot_magnetometer_read(client, &out, &error) == PILOT_OK);
        assert(out.last_update_ms == -9007199254740999LL);
        assert(out.valid == true);
        assert(out.x_microtesla == 1.25);
        assert(out.y_microtesla == 1.25);
        assert(out.z_microtesla == 1.25);
        assert(out.magnitude_microtesla == 1.25);
        assert(out.sequence == large_number);
        pilot_magnetometer_read_clear(&out);
        pilot_magnetometer_read_clear(&out);
    }
    {
        pilot_location_read_cell_result out = {0};
        assert(pilot_location_read_cell(client, &out, &error) == PILOT_OK);
        assert(!strcmp(out.state, "sample"));
        assert(out.valid == true);
        assert(out.latitude == 1.25);
        assert(out.longitude == 1.25);
        assert(out.radius_m == 1.25);
        assert(out.age_seconds == 42);
        assert(!strcmp(out.detail, "sample"));
        pilot_location_read_cell_clear(&out);
        pilot_location_read_cell_clear(&out);
    }
    {
        pilot_gps_read_result out = {0};
        assert(pilot_gps_read(client, &out, &error) == PILOT_OK);
        pilot_gps_read_clear(&out);
        pilot_gps_read_clear(&out);
    }
    {
        pilot_control_get_outputs_result out = {0};
        assert(pilot_control_get_outputs(client, &out, &error) == PILOT_OK);
        assert(out.channels_count == 2 && out.channels);
        assert(out.channels[0].channel == 42);
        assert(out.channels[0].mode == 42);
        assert(out.channels[0].value == -23);
        assert(out.channels[0].enabled == true);
        assert(out.channels[0].digital_supported == true);
        assert(out.debug_active == true);
        assert(out.last_remote_rx_ms == -9007199254740999LL);
        pilot_control_get_outputs_clear(&out);
        pilot_control_get_outputs_clear(&out);
    }
    {
        pilot_control_debug_begin_result out = {0};
        assert(pilot_control_debug_begin(client, &out, &error) == PILOT_OK);
        assert(out.accepted == true);
        assert(!strcmp(out.reason, "sample"));
        pilot_control_debug_begin_clear(&out);
        pilot_control_debug_begin_clear(&out);
    }
    {
        pilot_control_debug_set_result out = {0};
        assert(pilot_control_debug_set(client, 42, 42, -23, true, &out, &error) == PILOT_OK);
        assert(out.accepted == true);
        assert(!strcmp(out.reason, "sample"));
        pilot_control_debug_set_clear(&out);
        pilot_control_debug_set_clear(&out);
    }
    {
        pilot_control_debug_keepalive_result out = {0};
        assert(pilot_control_debug_keepalive(client, &out, &error) == PILOT_OK);
        assert(out.active == true);
        pilot_control_debug_keepalive_clear(&out);
        pilot_control_debug_keepalive_clear(&out);
    }
    {
        pilot_control_debug_end_result out = {0};
        assert(pilot_control_debug_end(client, &out, &error) == PILOT_OK);
        assert(out.ended == true);
        pilot_control_debug_end_clear(&out);
        pilot_control_debug_end_clear(&out);
    }
    {
        pilot_media_read_result out = {0};
        assert(pilot_media_read(client, &out, &error) == PILOT_OK);
        pilot_media_read_clear(&out);
        pilot_media_read_clear(&out);
    }
    {
        pilot_audio_read_spectrum_result out = {0};
        assert(pilot_audio_read_spectrum(client, &out, &error) == PILOT_OK);
        assert(out.available == true);
        assert(out.sample_rate == 42);
        assert(out.captured_ms == -9007199254740999LL);
        assert(out.sequence == large_number);
        assert(out.rms_dbfs == 1.25);
        assert(out.peak_dbfs == 1.25);
        assert(out.levels.size == 2 && out.levels.data[0] == 231);
        pilot_audio_read_spectrum_clear(&out);
        pilot_audio_read_spectrum_clear(&out);
    }
    {
        pilot_audio_get_volume_result out = {0};
        assert(pilot_audio_get_volume(client, &out, &error) == PILOT_OK);
        assert(out.available == true);
        assert(out.input_volume == 42);
        assert(out.output_volume == 42);
        pilot_audio_get_volume_clear(&out);
        pilot_audio_get_volume_clear(&out);
    }
    {
        pilot_audio_set_volume_result out = {0};
        assert(pilot_audio_set_volume(client, "sample", 42, &out, &error) == PILOT_OK);
        assert(out.accepted == true);
        assert(out.actual_volume == 42);
        assert(!strcmp(out.reason, "sample"));
        pilot_audio_set_volume_clear(&out);
        pilot_audio_set_volume_clear(&out);
    }
    {
        pilot_camera_capture_preview_result out = {0};
        assert(pilot_camera_capture_preview(client, &out, &error) == PILOT_OK);
        assert(out.success == true);
        assert(out.width == 42);
        assert(out.height == 42);
        assert(out.stride_bytes == 42);
        assert(out.captured_ms == -9007199254740999LL);
        assert(out.rgb565.size == 2 && out.rgb565.data[0] == 231);
        assert(!strcmp(out.reason, "sample"));
        pilot_camera_capture_preview_clear(&out);
        pilot_camera_capture_preview_clear(&out);
    }
    {
        pilot_connection_get_stats_result out = {0};
        assert(pilot_connection_get_stats(client, &out, &error) == PILOT_OK);
        assert(out.endpoints_count == 2 && out.endpoints);
        assert(!strcmp(out.endpoints[0].type, "sample"));
        assert(out.endpoints[0].connected == true);
        assert(out.endpoints[0].active == true);
        assert(out.endpoints[0].subscribers == -23);
        assert(out.endpoints[0].rtt_us == large_number);
        assert(out.endpoints[0].bytes_sent == large_number);
        assert(out.endpoints[0].bytes_lost == large_number);
        assert(out.endpoints[0].max_datagram_length == 42);
        pilot_connection_get_stats_clear(&out);
        pilot_connection_get_stats_clear(&out);
    }
    {
        pilot_diagnostics_read_result out = {0};
        assert(pilot_diagnostics_read(client, &out, &error) == PILOT_OK);
        assert(!strcmp(out.json, "sample"));
        pilot_diagnostics_read_clear(&out);
        pilot_diagnostics_read_clear(&out);
    }
    {
        pilot_network_read_result out = {0};
        assert(pilot_network_read(client, &out, &error) == PILOT_OK);
        assert(!strcmp(out.json, "sample"));
        pilot_network_read_clear(&out);
        pilot_network_read_clear(&out);
    }
    {
        pilot_connection_request_reconnect_result out = {0};
        assert(pilot_connection_request_reconnect(client, "sample", &out, &error) == PILOT_OK);
        assert(out.accepted == true);
        assert(!strcmp(out.reason, "sample"));
        pilot_connection_request_reconnect_clear(&out);
        pilot_connection_request_reconnect_clear(&out);
    }
    {
        pilot_selfcheck_read_result out = {0};
        assert(pilot_selfcheck_read(client, &out, &error) == PILOT_OK);
        assert(!strcmp(out.json, "sample"));
        pilot_selfcheck_read_clear(&out);
        pilot_selfcheck_read_clear(&out);
    }
    {
        pilot_selfcheck_run_result out = {0};
        assert(pilot_selfcheck_run(client, &out, &error) == PILOT_OK);
        assert(out.accepted == true);
        assert(!strcmp(out.reason, "sample"));
        pilot_selfcheck_run_clear(&out);
        pilot_selfcheck_run_clear(&out);
    }
    {
        pilot_network_get_recovery_policy_result out = {0};
        assert(pilot_network_get_recovery_policy(client, &out, &error) == PILOT_OK);
        assert(out.ignored == true);
        pilot_network_get_recovery_policy_clear(&out);
        pilot_network_get_recovery_policy_clear(&out);
    }
    {
        pilot_network_set_recovery_mode_result out = {0};
        assert(pilot_network_set_recovery_mode(client, "sample", &out, &error) == PILOT_OK);
        assert(out.ignored == true);
        pilot_network_set_recovery_mode_clear(&out);
        pilot_network_set_recovery_mode_clear(&out);
    }
    {
        pilot_fan_get_config_result out = {0};
        assert(pilot_fan_get_config(client, &out, &error) == PILOT_OK);
        assert(!strcmp(out.json, "sample"));
        pilot_fan_get_config_clear(&out);
        pilot_fan_get_config_clear(&out);
    }
    {
        pilot_fan_set_config_result out = {0};
        assert(pilot_fan_set_config(client, "sample", &out, &error) == PILOT_OK);
        assert(!strcmp(out.json, "sample"));
        pilot_fan_set_config_clear(&out);
        pilot_fan_set_config_clear(&out);
    }
}
static unsigned public_event_counts[7];
static void public_on_control(const pilot_control_event *event, void *userdata)
{
    assert(userdata == public_event_counts);
    public_event_counts[0]++;
    assert(event->signals_count == 2 && event->signals[0] == -23);
    assert(event->last_rx_ms == -9007199254740999LL);
}
static void public_on_imu(const pilot_imu_event *event, void *userdata)
{
    assert(userdata == public_event_counts);
    public_event_counts[1]++;
    assert(event->last_update_ms == -9007199254740999LL);
    assert(event->has_imu == true);
    assert(event->gyro_x == 1.25);
    assert(event->gyro_y == 1.25);
    assert(event->gyro_z == 1.25);
    assert(event->accel_x == 1.25);
    assert(event->accel_y == 1.25);
    assert(event->accel_z == 1.25);
}
static void public_on_magnetometer(const pilot_magnetometer_event *event, void *userdata)
{
    assert(userdata == public_event_counts);
    public_event_counts[2]++;
    assert(event->last_update_ms == -9007199254740999LL);
    assert(event->valid == true);
    assert(event->x_microtesla == 1.25);
    assert(event->y_microtesla == 1.25);
    assert(event->z_microtesla == 1.25);
    assert(event->magnitude_microtesla == 1.25);
    assert(event->sequence == large_number);
}
static void public_on_connection(const pilot_connection_event *event, void *userdata)
{
    assert(userdata == public_event_counts);
    public_event_counts[3]++;
    assert(!strcmp(event->type, "sample"));
    assert(event->connected == true);
    assert(event->subscribe_count == -23);
    assert(event->is_active == true);
}
static void public_on_network(const pilot_network_event *event, void *userdata)
{
    assert(userdata == public_event_counts);
    public_event_counts[4]++;
    assert(!strcmp(event->json, "sample"));
}
static void public_on_selfcheck(const pilot_selfcheck_event *event, void *userdata)
{
    assert(userdata == public_event_counts);
    public_event_counts[5]++;
    assert(!strcmp(event->json, "sample"));
}
static void public_on_cellular(const pilot_cellular_event *event, void *userdata)
{
    assert(userdata == public_event_counts);
    public_event_counts[6]++;
    assert(!strcmp(event->json, "sample"));
}
static void exercise_public_watches(pilot_client *client, bool enable)
{
    pilot_error error;
    assert(pilot_watch_control(client, enable ? public_on_control : NULL, public_event_counts, &error) == PILOT_OK);
    assert(pilot_watch_imu(client, enable ? public_on_imu : NULL, public_event_counts, &error) == PILOT_OK);
    assert(pilot_watch_magnetometer(client, enable ? public_on_magnetometer : NULL, public_event_counts, &error) == PILOT_OK);
    assert(pilot_watch_connection(client, enable ? public_on_connection : NULL, public_event_counts, &error) == PILOT_OK);
    assert(pilot_watch_network(client, enable ? public_on_network : NULL, public_event_counts, &error) == PILOT_OK);
    assert(pilot_watch_selfcheck(client, enable ? public_on_selfcheck : NULL, public_event_counts, &error) == PILOT_OK);
    assert(pilot_watch_cellular(client, enable ? public_on_cellular : NULL, public_event_counts, &error) == PILOT_OK);
}
