#!/usr/bin/env python3
"""Generate the typed C binding and reference from the checked-in ABI snapshot."""
import argparse
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
TYPES = {"b": ("bool", "boolean"), "s": ("const char *", "string"),
         "i": ("int32_t", "i32"), "u": ("uint32_t", "u32"), "q": ("uint16_t", "u16"),
         "x": ("int64_t", "i64"), "t": ("uint64_t", "u64"), "d": ("double", "real")}


def snake(name):
    name = name.replace("P2P", "P2p")
    name = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1_\2", name)
    return re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", name).lower()


def ctype(arg):
    return TYPES.get(arg["type"], ("const pilot_value *", ""))[0]


def render():
    data = json.loads((ROOT / "protocol/interfaces.json").read_text())
    services = data["services"]
    header = ['/* Generated by scripts/generate.py. Do not edit. */', '#ifndef PILOT_API_H',
              '#define PILOT_API_H', '#include "pilot.h"', '#ifdef __cplusplus', 'extern "C" {', '#endif']
    source = ['/* Generated by scripts/generate.py. Do not edit. */', '#include "pilot/api.h"', '#include <string.h>']
    methods = [(s, m) for s in services for m in s['methods']]
    signals = [(s, m) for s in services for m in s['signals']]
    header += ['typedef enum {'] + [f'    PILOT_SERVICE_{s["key"].upper()},' for s in services] + ['} pilot_service_id;']
    header += ['typedef enum {'] + [f'    PILOT_METHOD_{s["key"].upper()}_{snake(m["name"]).upper()},' for s, m in methods] + ['} pilot_method_id;']
    header += ['typedef enum {'] + [f'    PILOT_SIGNAL_{s["key"].upper()}_{snake(m["name"]).upper()},' for s, m in signals] + ['} pilot_signal_id;']
    source += ['const pilot_service pilot_services[] = {'] + [
        f'    {{"{s["name"]}", "{s["path"]}", "{s["interface"]}"}},' for s in services] + ['};',
        'const size_t pilot_service_count = sizeof(pilot_services) / sizeof(pilot_services[0]);',
        'const pilot_method pilot_methods[] = {']
    for s, m in methods:
        sig = lambda d: ''.join(a['type'] for a in m['args'] if a['direction'] == d)
        source.append(f'    {{PILOT_SERVICE_{s["key"].upper()}, "{m["name"]}", "{sig("in")}", "{sig("out")}"}},')
    source += ['};', 'const size_t pilot_method_count = sizeof(pilot_methods) / sizeof(pilot_methods[0]);',
               'const pilot_signal pilot_signals[] = {']
    for s, m in signals:
        sig = ''.join(a['type'] for a in m['args'])
        source.append(f'    {{PILOT_SERVICE_{s["key"].upper()}, "{m["name"]}", "{sig}"}},')
    source += ['};', 'const size_t pilot_signal_count = sizeof(pilot_signals) / sizeof(pilot_signals[0]);']
    docs = ['# D-Bus 接口清单', '', '由 `protocol/interfaces.json` 自动生成。对应工作区快照，不代表所有旧固件均支持。',
            '', '返回值中的字符串、数组、字典由结果对象持有，使用后调用对应 `_clear()`；重复调用前也要先清理。',
            '信号参数按下面的顺序从 `pilot_reply_at()` 读取，仅在回调期间有效。', '']
    for s in services:
        docs += [f'## {s["name"]}', '', f'- 对象：`{s["path"]}`', f'- 接口：`{s["interface"]}`', '']
        for m in s['methods']:
            name = 'pilot_' + s['key'] + '_' + snake(m['name'])
            result = name + '_result'
            inputs = [a for a in m['args'] if a['direction'] == 'in']
            outputs = [a for a in m['args'] if a['direction'] == 'out']
            header += ['typedef struct {'] + [f'    {ctype(a)} {snake(a["name"])};' for a in outputs] + [
                '    pilot_reply *_reply;', f'}} {result};']
            params = ['pilot_client *client'] + [f'{ctype(a)} {snake(a["name"])}' for a in inputs] + [f'{result} *out', 'pilot_error *error']
            proto = f'int {name}({", ".join(params)})'
            header += [proto + ';', f'void {name}_clear({result} *out);', '']
            source += [proto, '{', '    if (!out) {',
                       '        if (error) { memset(error, 0, sizeof(*error)); error->code = PILOT_INVALID_ARGUMENT;',
                       '            strcpy(error->message, "Missing output argument"); }',
                       '        return PILOT_INVALID_ARGUMENT;', '    }', '    memset(out, 0, sizeof(*out));']
            if inputs:
                source += [f'    pilot_value args[{len(inputs)}] = {{0}};']
                for i, a in enumerate(inputs):
                    source += [f"    args[{i}].type = '{a['type']}';", f'    args[{i}].as.{TYPES[a["type"]][1]} = {snake(a["name"])};']
            source += [f'    int rc = pilot_call(client, PILOT_METHOD_{s["key"].upper()}_{snake(m["name"]).upper()},',
                       f'                        {"args" if inputs else "NULL"}, {len(inputs)}, &out->_reply, error);',
                       '    if (rc != PILOT_OK) return rc;']
            for i, a in enumerate(outputs):
                value = f'pilot_reply_at(out->_reply, {i})'
                if a['type'] in TYPES:
                    value += '->as.' + TYPES[a['type']][1]
                source.append(f'    out->{snake(a["name"])} = {value};')
            source += ['    return PILOT_OK;', '}', f'void {name}_clear({result} *out)', '{',
                       '    if (out) { pilot_reply_free(out->_reply); memset(out, 0, sizeof(*out)); }', '}']
            fmt = lambda args: ', '.join(f'{a["name"]}: `{a["type"]}`' for a in args) or '无'
            docs += [f'### {m["name"]}', f'函数：`{name}()`', f'- 输入：{fmt(inputs)}', f'- 输出：{fmt(outputs)}', '']
        for m in s['signals']:
            docs += [f'### 信号 {m["name"]}', f'枚举：`PILOT_SIGNAL_{s["key"].upper()}_{snake(m["name"]).upper()}`',
                     ', '.join(f'{a["name"]}: `{a["type"]}`' for a in m['args']), '']
    header += ['#ifdef __cplusplus', '}', '#endif', '#endif']
    return {ROOT / 'include/pilot/api.h': '\n'.join(header) + '\n',
            ROOT / 'src/api.c': '\n'.join(source) + '\n', ROOT / 'docs/API.md': '\n'.join(docs).rstrip() + '\n'}


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for path, content in render().items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                raise SystemExit(f'Generated file out of date: {path}')
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding='utf-8')
