/* Generated by scripts/generate.py. Do not edit. */
#ifndef PILOT_API_H
#define PILOT_API_H
#include "pilot.h"
#ifdef __cplusplus
extern "C" {
#endif
typedef struct {
    const char * response;
    void *_private; /* Library-owned; never modify or copy ownership. */
} pilot_battery_request_result;
PILOT_API void pilot_battery_request_clear(pilot_battery_request_result *out);
PILOT_API int pilot_battery_request(pilot_client *client, const char * request, pilot_battery_request_result *out, pilot_error *error);

typedef struct {
    int32_t index;
    void *_private; /* Library-owned; never modify or copy ownership. */
} pilot_connection_get_active_result;
PILOT_API void pilot_connection_get_active_clear(pilot_connection_get_active_result *out);
PILOT_API int pilot_connection_get_active(pilot_client *client, pilot_connection_get_active_result *out, pilot_error *error);

typedef struct {
    const char * type;
    bool connected;
    const char * ip;
    uint16_t port;
    int32_t subscribe_count;
    bool is_active;
    void *_private; /* Library-owned; never modify or copy ownership. */
} pilot_connection_get_relay_result;
PILOT_API void pilot_connection_get_relay_clear(pilot_connection_get_relay_result *out);
PILOT_API int pilot_connection_get_relay(pilot_client *client, pilot_connection_get_relay_result *out, pilot_error *error);

typedef struct {
    const char * type;
    bool connected;
    const char * ip;
    uint16_t port;
    int32_t subscribe_count;
    bool is_active;
    void *_private; /* Library-owned; never modify or copy ownership. */
} pilot_connection_get_p2p_result;
PILOT_API void pilot_connection_get_p2p_clear(pilot_connection_get_p2p_result *out);
PILOT_API int pilot_connection_get_p2p(pilot_client *client, pilot_connection_get_p2p_result *out, pilot_error *error);

typedef struct {
    const pilot_endpoint * endpoints;
    size_t endpoints_count;
    int32_t active_index;
    void *_private; /* Library-owned; never modify or copy ownership. */
} pilot_connection_get_status_result;
PILOT_API void pilot_connection_get_status_clear(pilot_connection_get_status_result *out);
PILOT_API int pilot_connection_get_status(pilot_client *client, pilot_connection_get_status_result *out, pilot_error *error);

typedef struct {
    const int32_t * signals;
    size_t signals_count;
    int64_t last_rx_ms;
    void *_private; /* Library-owned; never modify or copy ownership. */
} pilot_control_read_result;
PILOT_API void pilot_control_read_clear(pilot_control_read_result *out);
PILOT_API int pilot_control_read(pilot_client *client, pilot_control_read_result *out, pilot_error *error);

typedef struct {
    bool applied;
    void *_private; /* Library-owned; never modify or copy ownership. */
} pilot_control_set_result;
PILOT_API void pilot_control_set_clear(pilot_control_set_result *out);
PILOT_API int pilot_control_set(pilot_client *client, int32_t channel, int32_t value, pilot_control_set_result *out, pilot_error *error);

typedef struct {
    int64_t last_sample_ms;
    bool valid;
    double gyro_x;
    double gyro_y;
    double gyro_z;
    double accel_x;
    double accel_y;
    double accel_z;
    void *_private; /* Library-owned; never modify or copy ownership. */
} pilot_imu_read_result;
PILOT_API void pilot_imu_read_clear(pilot_imu_read_result *out);
PILOT_API int pilot_imu_read(pilot_client *client, pilot_imu_read_result *out, pilot_error *error);

typedef struct {
    int64_t last_update_ms;
    bool has_imu;
    double gyro_x;
    double gyro_y;
    double gyro_z;
    double accel_x;
    double accel_y;
    double accel_z;
    double temperature;
    double memory_usage;
    double cpu_usage;
    double disk_usage;
    int32_t battery_percent;
    double voltage;
    int32_t rssi_dbm;
    bool has_gps;
    double latitude;
    double longitude;
    double altitude;
    int32_t gps_satellites;
    double hdop;
    void *_private; /* Library-owned; never modify or copy ownership. */
} pilot_device_read_result;
PILOT_API void pilot_device_read_clear(pilot_device_read_result *out);
PILOT_API int pilot_device_read(pilot_client *client, pilot_device_read_result *out, pilot_error *error);

typedef struct {
    int64_t last_update_ms;
    bool valid;
    double x_microtesla;
    double y_microtesla;
    double z_microtesla;
    double magnitude_microtesla;
    uint64_t sequence;
    void *_private; /* Library-owned; never modify or copy ownership. */
} pilot_magnetometer_read_result;
PILOT_API void pilot_magnetometer_read_clear(pilot_magnetometer_read_result *out);
PILOT_API int pilot_magnetometer_read(pilot_client *client, pilot_magnetometer_read_result *out, pilot_error *error);

typedef struct {
    const char * state;
    bool valid;
    double latitude;
    double longitude;
    double radius_m;
    uint32_t age_seconds;
    const char * detail;
    void *_private; /* Library-owned; never modify or copy ownership. */
} pilot_location_read_cell_result;
PILOT_API void pilot_location_read_cell_clear(pilot_location_read_cell_result *out);
PILOT_API int pilot_location_read_cell(pilot_client *client, pilot_location_read_cell_result *out, pilot_error *error);

typedef struct {
    const pilot_properties * status;
    void *_private; /* Library-owned; never modify or copy ownership. */
} pilot_gps_read_result;
PILOT_API void pilot_gps_read_clear(pilot_gps_read_result *out);
PILOT_API int pilot_gps_read(pilot_client *client, pilot_gps_read_result *out, pilot_error *error);

typedef struct {
    const pilot_channel_output * channels;
    size_t channels_count;
    bool debug_active;
    int64_t last_remote_rx_ms;
    void *_private; /* Library-owned; never modify or copy ownership. */
} pilot_control_get_outputs_result;
PILOT_API void pilot_control_get_outputs_clear(pilot_control_get_outputs_result *out);
PILOT_API int pilot_control_get_outputs(pilot_client *client, pilot_control_get_outputs_result *out, pilot_error *error);

typedef struct {
    bool accepted;
    const char * reason;
    void *_private; /* Library-owned; never modify or copy ownership. */
} pilot_control_debug_begin_result;
PILOT_API void pilot_control_debug_begin_clear(pilot_control_debug_begin_result *out);
PILOT_API int pilot_control_debug_begin(pilot_client *client, pilot_control_debug_begin_result *out, pilot_error *error);

typedef struct {
    bool accepted;
    const char * reason;
    void *_private; /* Library-owned; never modify or copy ownership. */
} pilot_control_debug_set_result;
PILOT_API void pilot_control_debug_set_clear(pilot_control_debug_set_result *out);
PILOT_API int pilot_control_debug_set(pilot_client *client, uint32_t channel, uint32_t mode, int32_t value, bool enabled, pilot_control_debug_set_result *out, pilot_error *error);

typedef struct {
    bool active;
    void *_private; /* Library-owned; never modify or copy ownership. */
} pilot_control_debug_keepalive_result;
PILOT_API void pilot_control_debug_keepalive_clear(pilot_control_debug_keepalive_result *out);
PILOT_API int pilot_control_debug_keepalive(pilot_client *client, pilot_control_debug_keepalive_result *out, pilot_error *error);

typedef struct {
    bool ended;
    void *_private; /* Library-owned; never modify or copy ownership. */
} pilot_control_debug_end_result;
PILOT_API void pilot_control_debug_end_clear(pilot_control_debug_end_result *out);
PILOT_API int pilot_control_debug_end(pilot_client *client, pilot_control_debug_end_result *out, pilot_error *error);

typedef struct {
    const pilot_properties * status;
    void *_private; /* Library-owned; never modify or copy ownership. */
} pilot_media_read_result;
PILOT_API void pilot_media_read_clear(pilot_media_read_result *out);
PILOT_API int pilot_media_read(pilot_client *client, pilot_media_read_result *out, pilot_error *error);

typedef struct {
    bool available;
    uint32_t sample_rate;
    int64_t captured_ms;
    uint64_t sequence;
    double rms_dbfs;
    double peak_dbfs;
    pilot_bytes levels;
    void *_private; /* Library-owned; never modify or copy ownership. */
} pilot_audio_read_spectrum_result;
PILOT_API void pilot_audio_read_spectrum_clear(pilot_audio_read_spectrum_result *out);
PILOT_API int pilot_audio_read_spectrum(pilot_client *client, pilot_audio_read_spectrum_result *out, pilot_error *error);

typedef struct {
    bool available;
    uint32_t input_volume;
    uint32_t output_volume;
    void *_private; /* Library-owned; never modify or copy ownership. */
} pilot_audio_get_volume_result;
PILOT_API void pilot_audio_get_volume_clear(pilot_audio_get_volume_result *out);
PILOT_API int pilot_audio_get_volume(pilot_client *client, pilot_audio_get_volume_result *out, pilot_error *error);

typedef struct {
    bool accepted;
    uint32_t actual_volume;
    const char * reason;
    void *_private; /* Library-owned; never modify or copy ownership. */
} pilot_audio_set_volume_result;
PILOT_API void pilot_audio_set_volume_clear(pilot_audio_set_volume_result *out);
PILOT_API int pilot_audio_set_volume(pilot_client *client, const char * target, uint32_t volume, pilot_audio_set_volume_result *out, pilot_error *error);

typedef struct {
    bool success;
    uint32_t width;
    uint32_t height;
    uint32_t stride_bytes;
    int64_t captured_ms;
    pilot_bytes rgb565;
    const char * reason;
    void *_private; /* Library-owned; never modify or copy ownership. */
} pilot_camera_capture_preview_result;
PILOT_API void pilot_camera_capture_preview_clear(pilot_camera_capture_preview_result *out);
PILOT_API int pilot_camera_capture_preview(pilot_client *client, pilot_camera_capture_preview_result *out, pilot_error *error);

typedef struct {
    const pilot_transport_stats * endpoints;
    size_t endpoints_count;
    void *_private; /* Library-owned; never modify or copy ownership. */
} pilot_connection_get_stats_result;
PILOT_API void pilot_connection_get_stats_clear(pilot_connection_get_stats_result *out);
PILOT_API int pilot_connection_get_stats(pilot_client *client, pilot_connection_get_stats_result *out, pilot_error *error);

typedef struct {
    const char * json;
    void *_private; /* Library-owned; never modify or copy ownership. */
} pilot_diagnostics_read_result;
PILOT_API void pilot_diagnostics_read_clear(pilot_diagnostics_read_result *out);
PILOT_API int pilot_diagnostics_read(pilot_client *client, pilot_diagnostics_read_result *out, pilot_error *error);

typedef struct {
    const char * json;
    void *_private; /* Library-owned; never modify or copy ownership. */
} pilot_network_read_result;
PILOT_API void pilot_network_read_clear(pilot_network_read_result *out);
PILOT_API int pilot_network_read(pilot_client *client, pilot_network_read_result *out, pilot_error *error);

typedef struct {
    bool accepted;
    const char * reason;
    void *_private; /* Library-owned; never modify or copy ownership. */
} pilot_connection_request_reconnect_result;
PILOT_API void pilot_connection_request_reconnect_clear(pilot_connection_request_reconnect_result *out);
PILOT_API int pilot_connection_request_reconnect(pilot_client *client, const char * endpoint, pilot_connection_request_reconnect_result *out, pilot_error *error);

typedef struct {
    const char * json;
    void *_private; /* Library-owned; never modify or copy ownership. */
} pilot_selfcheck_read_result;
PILOT_API void pilot_selfcheck_read_clear(pilot_selfcheck_read_result *out);
PILOT_API int pilot_selfcheck_read(pilot_client *client, pilot_selfcheck_read_result *out, pilot_error *error);

typedef struct {
    bool accepted;
    const char * reason;
    void *_private; /* Library-owned; never modify or copy ownership. */
} pilot_selfcheck_run_result;
PILOT_API void pilot_selfcheck_run_clear(pilot_selfcheck_run_result *out);
PILOT_API int pilot_selfcheck_run(pilot_client *client, pilot_selfcheck_run_result *out, pilot_error *error);

typedef struct {
    bool ignored;
    void *_private; /* Library-owned; never modify or copy ownership. */
} pilot_network_get_recovery_policy_result;
PILOT_API void pilot_network_get_recovery_policy_clear(pilot_network_get_recovery_policy_result *out);
PILOT_API int pilot_network_get_recovery_policy(pilot_client *client, pilot_network_get_recovery_policy_result *out, pilot_error *error);

typedef struct {
    bool ignored;
    void *_private; /* Library-owned; never modify or copy ownership. */
} pilot_network_set_recovery_mode_result;
PILOT_API void pilot_network_set_recovery_mode_clear(pilot_network_set_recovery_mode_result *out);
PILOT_API int pilot_network_set_recovery_mode(pilot_client *client, const char * mode, pilot_network_set_recovery_mode_result *out, pilot_error *error);

typedef struct {
    const char * json;
    void *_private; /* Library-owned; never modify or copy ownership. */
} pilot_fan_get_config_result;
PILOT_API void pilot_fan_get_config_clear(pilot_fan_get_config_result *out);
PILOT_API int pilot_fan_get_config(pilot_client *client, pilot_fan_get_config_result *out, pilot_error *error);

typedef struct {
    const char * json;
    void *_private; /* Library-owned; never modify or copy ownership. */
} pilot_fan_set_config_result;
PILOT_API void pilot_fan_set_config_clear(pilot_fan_set_config_result *out);
PILOT_API int pilot_fan_set_config(pilot_client *client, const char * request, pilot_fan_set_config_result *out, pilot_error *error);

typedef struct {
    const int32_t * signals;
    size_t signals_count;
    int64_t last_rx_ms;
    void *_private; /* Library-owned; never modify or copy ownership. */
} pilot_control_event;
typedef void (*pilot_control_callback)(const pilot_control_event *event, void *userdata);
PILOT_API int pilot_watch_control(pilot_client *client, pilot_control_callback callback, void *userdata, pilot_error *error);

typedef struct {
    int64_t last_update_ms;
    bool has_imu;
    double gyro_x;
    double gyro_y;
    double gyro_z;
    double accel_x;
    double accel_y;
    double accel_z;
    void *_private; /* Library-owned; never modify or copy ownership. */
} pilot_imu_event;
typedef void (*pilot_imu_callback)(const pilot_imu_event *event, void *userdata);
PILOT_API int pilot_watch_imu(pilot_client *client, pilot_imu_callback callback, void *userdata, pilot_error *error);

typedef struct {
    int64_t last_update_ms;
    bool valid;
    double x_microtesla;
    double y_microtesla;
    double z_microtesla;
    double magnitude_microtesla;
    uint64_t sequence;
    void *_private; /* Library-owned; never modify or copy ownership. */
} pilot_magnetometer_event;
typedef void (*pilot_magnetometer_callback)(const pilot_magnetometer_event *event, void *userdata);
PILOT_API int pilot_watch_magnetometer(pilot_client *client, pilot_magnetometer_callback callback, void *userdata, pilot_error *error);

typedef struct {
    const char * type;
    bool connected;
    int32_t subscribe_count;
    bool is_active;
    void *_private; /* Library-owned; never modify or copy ownership. */
} pilot_connection_event;
typedef void (*pilot_connection_callback)(const pilot_connection_event *event, void *userdata);
PILOT_API int pilot_watch_connection(pilot_client *client, pilot_connection_callback callback, void *userdata, pilot_error *error);

typedef struct {
    const char * json;
    void *_private; /* Library-owned; never modify or copy ownership. */
} pilot_network_event;
typedef void (*pilot_network_callback)(const pilot_network_event *event, void *userdata);
PILOT_API int pilot_watch_network(pilot_client *client, pilot_network_callback callback, void *userdata, pilot_error *error);

typedef struct {
    const char * json;
    void *_private; /* Library-owned; never modify or copy ownership. */
} pilot_selfcheck_event;
typedef void (*pilot_selfcheck_callback)(const pilot_selfcheck_event *event, void *userdata);
PILOT_API int pilot_watch_selfcheck(pilot_client *client, pilot_selfcheck_callback callback, void *userdata, pilot_error *error);

typedef struct {
    const char * json;
    void *_private; /* Library-owned; never modify or copy ownership. */
} pilot_cellular_event;
typedef void (*pilot_cellular_callback)(const pilot_cellular_event *event, void *userdata);
PILOT_API int pilot_watch_cellular(pilot_client *client, pilot_cellular_callback callback, void *userdata, pilot_error *error);

#ifdef __cplusplus
}
#endif
#endif
