/* Generated by scripts/generate.py. Do not edit. */
#include "pilot/api.h"
#include "private/protocol.h"
#include <stdlib.h>
#include <string.h>
static int api_error(pilot_error *error, int code)
{
    if (error) { memset(error, 0, sizeof(*error)); error->code = code;
        strncpy(error->message, pilot_status_string(code), sizeof(error->message) - 1); }
    return code;
}
const pilot_service pilot_services[] = {
    {"tech.andless.RealTimeComm", "/tech/andless/RealTimeComm/Status", "tech.andless.RealTimeComm.Status1"},
    {"tech.andless.SelfCheck", "/tech/andless/SelfCheck/Report", "tech.andless.SelfCheck.Report1"},
    {"tech.andless.Fan", "/tech/andless/Fan", "tech.andless.Fan.Config1"},
    {"tech.andless.Modem", "/tech/andless/Modem", "tech.andless.Modem.Status1"},
};
const size_t pilot_service_count = sizeof(pilot_services) / sizeof(pilot_services[0]);
const pilot_method pilot_methods[] = {
    {PILOT_SERVICE_RTC, "BatteryCommand", "s", "s"},
    {PILOT_SERVICE_RTC, "GetActiveEndpoint", "", "i"},
    {PILOT_SERVICE_RTC, "GetCloudStatus", "", "sbsqib"},
    {PILOT_SERVICE_RTC, "GetP2PStatus", "", "sbsqib"},
    {PILOT_SERVICE_RTC, "GetAllStatus", "", "a(sbsqib)i"},
    {PILOT_SERVICE_RTC, "GetControlSignals", "", "aix"},
    {PILOT_SERVICE_RTC, "SetChannelOutput", "ii", "b"},
    {PILOT_SERVICE_RTC, "GetImuData", "", "xbdddddd"},
    {PILOT_SERVICE_RTC, "GetDeviceParam", "", "xbddddddddddidibdddid"},
    {PILOT_SERVICE_RTC, "GetMagnetometerData", "", "xbddddt"},
    {PILOT_SERVICE_RTC, "GetCellLocation", "", "sbdddus"},
    {PILOT_SERVICE_RTC, "GetGpsStatus", "", "a{sv}"},
    {PILOT_SERVICE_RTC, "GetChannelOutputStatus", "", "a(uuibb)bx"},
    {PILOT_SERVICE_RTC, "BeginChannelDebug", "", "bs"},
    {PILOT_SERVICE_RTC, "SetChannelDebug", "uuib", "bs"},
    {PILOT_SERVICE_RTC, "ChannelDebugKeepAlive", "", "b"},
    {PILOT_SERVICE_RTC, "EndChannelDebug", "", "b"},
    {PILOT_SERVICE_RTC, "GetMediaStatus", "", "a{sv}"},
    {PILOT_SERVICE_RTC, "GetAudioSpectrum", "", "buxtdday"},
    {PILOT_SERVICE_RTC, "GetAudioVolume", "", "buu"},
    {PILOT_SERVICE_RTC, "SetAudioVolume", "su", "bus"},
    {PILOT_SERVICE_RTC, "CaptureCameraPreview", "", "buuuxays"},
    {PILOT_SERVICE_RTC, "GetTransportStats", "", "a(sbbitttu)"},
    {PILOT_SERVICE_RTC, "GetDiagnosticStats", "", "s"},
    {PILOT_SERVICE_RTC, "GetNetworkDiagnostics", "", "s"},
    {PILOT_SERVICE_RTC, "RequestReconnect", "s", "bs"},
    {PILOT_SERVICE_SELFCHECK, "GetReport", "", "s"},
    {PILOT_SERVICE_SELFCHECK, "RunNow", "", "bs"},
    {PILOT_SERVICE_SELFCHECK, "GetNetworkRecoveryPolicy", "", "b"},
    {PILOT_SERVICE_SELFCHECK, "SetNetworkRecoveryMode", "s", "b"},
    {PILOT_SERVICE_FAN, "GetConfig", "", "s"},
    {PILOT_SERVICE_FAN, "SetConfig", "s", "s"},
};
const size_t pilot_method_count = sizeof(pilot_methods) / sizeof(pilot_methods[0]);
const pilot_signal pilot_signals[] = {
    {PILOT_SERVICE_RTC, "ControlSignalsChanged", "aix"},
    {PILOT_SERVICE_RTC, "ImuDataChanged", "xbdddddd"},
    {PILOT_SERVICE_RTC, "MagnetometerDataChanged", "xbddddt"},
    {PILOT_SERVICE_RTC, "EndpointStateChanged", "sbib"},
    {PILOT_SERVICE_RTC, "NetworkDiagnosticsChanged", "s"},
    {PILOT_SERVICE_SELFCHECK, "ReportChanged", "s"},
    {PILOT_SERVICE_MODEM, "CellInfoChanged", "s"},
};
const size_t pilot_signal_count = sizeof(pilot_signals) / sizeof(pilot_signals[0]);
void pilot_battery_request_clear(pilot_battery_request_result *out)
{
    if (!out) return;
    pilot_reply_free(out->_private);
    memset(out, 0, sizeof(*out));
}
static int pilot_battery_request_decode(const pilot_reply *reply, bool own, pilot_battery_request_result *out, pilot_error *error)
{
    (void)error;
    memset(out, 0, sizeof(*out));
    out->_private = own ? (void *)reply : NULL;
    out->response = pilot_reply_at(reply, 0)->as.string;
    return PILOT_OK;
}
int pilot_battery_request(pilot_client *client, const char * request, pilot_battery_request_result *out, pilot_error *error)
{
    if (!out) return api_error(error, PILOT_INVALID_ARGUMENT);
    memset(out, 0, sizeof(*out));
    pilot_reply *reply = NULL;
    pilot_value args[1] = {0};
    args[0].type = 's';
    args[0].as.string = request;
    int rc = pilot_call(client, PILOT_METHOD_RTC_BATTERY_COMMAND,
                        args, 1, &reply, error);
    if (rc != PILOT_OK) return rc;
    return pilot_battery_request_decode(reply, true, out, error);
}
void pilot_connection_get_active_clear(pilot_connection_get_active_result *out)
{
    if (!out) return;
    pilot_reply_free(out->_private);
    memset(out, 0, sizeof(*out));
}
static int pilot_connection_get_active_decode(const pilot_reply *reply, bool own, pilot_connection_get_active_result *out, pilot_error *error)
{
    (void)error;
    memset(out, 0, sizeof(*out));
    out->_private = own ? (void *)reply : NULL;
    out->index = pilot_reply_at(reply, 0)->as.i32;
    return PILOT_OK;
}
int pilot_connection_get_active(pilot_client *client, pilot_connection_get_active_result *out, pilot_error *error)
{
    if (!out) return api_error(error, PILOT_INVALID_ARGUMENT);
    memset(out, 0, sizeof(*out));
    pilot_reply *reply = NULL;
    int rc = pilot_call(client, PILOT_METHOD_RTC_GET_ACTIVE_ENDPOINT,
                        NULL, 0, &reply, error);
    if (rc != PILOT_OK) return rc;
    return pilot_connection_get_active_decode(reply, true, out, error);
}
void pilot_connection_get_relay_clear(pilot_connection_get_relay_result *out)
{
    if (!out) return;
    pilot_reply_free(out->_private);
    memset(out, 0, sizeof(*out));
}
static int pilot_connection_get_relay_decode(const pilot_reply *reply, bool own, pilot_connection_get_relay_result *out, pilot_error *error)
{
    (void)error;
    memset(out, 0, sizeof(*out));
    out->_private = own ? (void *)reply : NULL;
    out->type = pilot_reply_at(reply, 0)->as.string;
    out->connected = pilot_reply_at(reply, 1)->as.boolean;
    out->ip = pilot_reply_at(reply, 2)->as.string;
    out->port = pilot_reply_at(reply, 3)->as.u16;
    out->subscribe_count = pilot_reply_at(reply, 4)->as.i32;
    out->is_active = pilot_reply_at(reply, 5)->as.boolean;
    return PILOT_OK;
}
int pilot_connection_get_relay(pilot_client *client, pilot_connection_get_relay_result *out, pilot_error *error)
{
    if (!out) return api_error(error, PILOT_INVALID_ARGUMENT);
    memset(out, 0, sizeof(*out));
    pilot_reply *reply = NULL;
    int rc = pilot_call(client, PILOT_METHOD_RTC_GET_CLOUD_STATUS,
                        NULL, 0, &reply, error);
    if (rc != PILOT_OK) return rc;
    return pilot_connection_get_relay_decode(reply, true, out, error);
}
void pilot_connection_get_p2p_clear(pilot_connection_get_p2p_result *out)
{
    if (!out) return;
    pilot_reply_free(out->_private);
    memset(out, 0, sizeof(*out));
}
static int pilot_connection_get_p2p_decode(const pilot_reply *reply, bool own, pilot_connection_get_p2p_result *out, pilot_error *error)
{
    (void)error;
    memset(out, 0, sizeof(*out));
    out->_private = own ? (void *)reply : NULL;
    out->type = pilot_reply_at(reply, 0)->as.string;
    out->connected = pilot_reply_at(reply, 1)->as.boolean;
    out->ip = pilot_reply_at(reply, 2)->as.string;
    out->port = pilot_reply_at(reply, 3)->as.u16;
    out->subscribe_count = pilot_reply_at(reply, 4)->as.i32;
    out->is_active = pilot_reply_at(reply, 5)->as.boolean;
    return PILOT_OK;
}
int pilot_connection_get_p2p(pilot_client *client, pilot_connection_get_p2p_result *out, pilot_error *error)
{
    if (!out) return api_error(error, PILOT_INVALID_ARGUMENT);
    memset(out, 0, sizeof(*out));
    pilot_reply *reply = NULL;
    int rc = pilot_call(client, PILOT_METHOD_RTC_GET_P2P_STATUS,
                        NULL, 0, &reply, error);
    if (rc != PILOT_OK) return rc;
    return pilot_connection_get_p2p_decode(reply, true, out, error);
}
void pilot_connection_get_status_clear(pilot_connection_get_status_result *out)
{
    if (!out) return;
    free((void *)out->endpoints);
    pilot_reply_free(out->_private);
    memset(out, 0, sizeof(*out));
}
static int pilot_connection_get_status_decode(const pilot_reply *reply, bool own, pilot_connection_get_status_result *out, pilot_error *error)
{
    (void)error;
    memset(out, 0, sizeof(*out));
    out->_private = own ? (void *)reply : NULL;
    {
        const pilot_value *array = pilot_reply_at(reply, 0);
        pilot_endpoint *items = array->count ? calloc(array->count, sizeof(*items)) : NULL;
        if (array->count && !items) goto no_memory;
        out->endpoints = items;
        out->endpoints_count = array->count;
        for (size_t j = 0; j < array->count; ++j) {
            const pilot_value *item = pilot_value_at(array, j);
            items[j].type = pilot_value_at(item, 0)->as.string;
            items[j].connected = pilot_value_at(item, 1)->as.boolean;
            items[j].ip = pilot_value_at(item, 2)->as.string;
            items[j].port = pilot_value_at(item, 3)->as.u16;
            items[j].subscribe_count = pilot_value_at(item, 4)->as.i32;
            items[j].is_active = pilot_value_at(item, 5)->as.boolean;
        }
    }
    out->active_index = pilot_reply_at(reply, 1)->as.i32;
    return PILOT_OK;
no_memory:
    pilot_connection_get_status_clear(out);
    return api_error(error, PILOT_NO_MEMORY);
}
int pilot_connection_get_status(pilot_client *client, pilot_connection_get_status_result *out, pilot_error *error)
{
    if (!out) return api_error(error, PILOT_INVALID_ARGUMENT);
    memset(out, 0, sizeof(*out));
    pilot_reply *reply = NULL;
    int rc = pilot_call(client, PILOT_METHOD_RTC_GET_ALL_STATUS,
                        NULL, 0, &reply, error);
    if (rc != PILOT_OK) return rc;
    return pilot_connection_get_status_decode(reply, true, out, error);
}
void pilot_control_read_clear(pilot_control_read_result *out)
{
    if (!out) return;
    free((void *)out->signals);
    pilot_reply_free(out->_private);
    memset(out, 0, sizeof(*out));
}
static int pilot_control_read_decode(const pilot_reply *reply, bool own, pilot_control_read_result *out, pilot_error *error)
{
    (void)error;
    memset(out, 0, sizeof(*out));
    out->_private = own ? (void *)reply : NULL;
    {
        const pilot_value *array = pilot_reply_at(reply, 0);
        int32_t *items = array->count ? calloc(array->count, sizeof(*items)) : NULL;
        if (array->count && !items) goto no_memory;
        out->signals = items;
        out->signals_count = array->count;
        for (size_t j = 0; j < array->count; ++j) {
            const pilot_value *item = pilot_value_at(array, j);
            items[j] = item->as.i32;
        }
    }
    out->last_rx_ms = pilot_reply_at(reply, 1)->as.i64;
    return PILOT_OK;
no_memory:
    pilot_control_read_clear(out);
    return api_error(error, PILOT_NO_MEMORY);
}
int pilot_control_read(pilot_client *client, pilot_control_read_result *out, pilot_error *error)
{
    if (!out) return api_error(error, PILOT_INVALID_ARGUMENT);
    memset(out, 0, sizeof(*out));
    pilot_reply *reply = NULL;
    int rc = pilot_call(client, PILOT_METHOD_RTC_GET_CONTROL_SIGNALS,
                        NULL, 0, &reply, error);
    if (rc != PILOT_OK) return rc;
    return pilot_control_read_decode(reply, true, out, error);
}
void pilot_control_set_clear(pilot_control_set_result *out)
{
    if (!out) return;
    pilot_reply_free(out->_private);
    memset(out, 0, sizeof(*out));
}
static int pilot_control_set_decode(const pilot_reply *reply, bool own, pilot_control_set_result *out, pilot_error *error)
{
    (void)error;
    memset(out, 0, sizeof(*out));
    out->_private = own ? (void *)reply : NULL;
    out->applied = pilot_reply_at(reply, 0)->as.boolean;
    return PILOT_OK;
}
int pilot_control_set(pilot_client *client, int32_t channel, int32_t value, pilot_control_set_result *out, pilot_error *error)
{
    if (!out) return api_error(error, PILOT_INVALID_ARGUMENT);
    memset(out, 0, sizeof(*out));
    pilot_reply *reply = NULL;
    pilot_value args[2] = {0};
    args[0].type = 'i';
    args[0].as.i32 = channel;
    args[1].type = 'i';
    args[1].as.i32 = value;
    int rc = pilot_call(client, PILOT_METHOD_RTC_SET_CHANNEL_OUTPUT,
                        args, 2, &reply, error);
    if (rc != PILOT_OK) return rc;
    return pilot_control_set_decode(reply, true, out, error);
}
void pilot_imu_read_clear(pilot_imu_read_result *out)
{
    if (!out) return;
    pilot_reply_free(out->_private);
    memset(out, 0, sizeof(*out));
}
static int pilot_imu_read_decode(const pilot_reply *reply, bool own, pilot_imu_read_result *out, pilot_error *error)
{
    (void)error;
    memset(out, 0, sizeof(*out));
    out->_private = own ? (void *)reply : NULL;
    out->last_sample_ms = pilot_reply_at(reply, 0)->as.i64;
    out->valid = pilot_reply_at(reply, 1)->as.boolean;
    out->gyro_x = pilot_reply_at(reply, 2)->as.real;
    out->gyro_y = pilot_reply_at(reply, 3)->as.real;
    out->gyro_z = pilot_reply_at(reply, 4)->as.real;
    out->accel_x = pilot_reply_at(reply, 5)->as.real;
    out->accel_y = pilot_reply_at(reply, 6)->as.real;
    out->accel_z = pilot_reply_at(reply, 7)->as.real;
    return PILOT_OK;
}
int pilot_imu_read(pilot_client *client, pilot_imu_read_result *out, pilot_error *error)
{
    if (!out) return api_error(error, PILOT_INVALID_ARGUMENT);
    memset(out, 0, sizeof(*out));
    pilot_reply *reply = NULL;
    int rc = pilot_call(client, PILOT_METHOD_RTC_GET_IMU_DATA,
                        NULL, 0, &reply, error);
    if (rc != PILOT_OK) return rc;
    return pilot_imu_read_decode(reply, true, out, error);
}
void pilot_device_read_clear(pilot_device_read_result *out)
{
    if (!out) return;
    pilot_reply_free(out->_private);
    memset(out, 0, sizeof(*out));
}
static int pilot_device_read_decode(const pilot_reply *reply, bool own, pilot_device_read_result *out, pilot_error *error)
{
    (void)error;
    memset(out, 0, sizeof(*out));
    out->_private = own ? (void *)reply : NULL;
    out->last_update_ms = pilot_reply_at(reply, 0)->as.i64;
    out->has_imu = pilot_reply_at(reply, 1)->as.boolean;
    out->gyro_x = pilot_reply_at(reply, 2)->as.real;
    out->gyro_y = pilot_reply_at(reply, 3)->as.real;
    out->gyro_z = pilot_reply_at(reply, 4)->as.real;
    out->accel_x = pilot_reply_at(reply, 5)->as.real;
    out->accel_y = pilot_reply_at(reply, 6)->as.real;
    out->accel_z = pilot_reply_at(reply, 7)->as.real;
    out->temperature = pilot_reply_at(reply, 8)->as.real;
    out->memory_usage = pilot_reply_at(reply, 9)->as.real;
    out->cpu_usage = pilot_reply_at(reply, 10)->as.real;
    out->disk_usage = pilot_reply_at(reply, 11)->as.real;
    out->battery_percent = pilot_reply_at(reply, 12)->as.i32;
    out->voltage = pilot_reply_at(reply, 13)->as.real;
    out->rssi_dbm = pilot_reply_at(reply, 14)->as.i32;
    out->has_gps = pilot_reply_at(reply, 15)->as.boolean;
    out->latitude = pilot_reply_at(reply, 16)->as.real;
    out->longitude = pilot_reply_at(reply, 17)->as.real;
    out->altitude = pilot_reply_at(reply, 18)->as.real;
    out->gps_satellites = pilot_reply_at(reply, 19)->as.i32;
    out->hdop = pilot_reply_at(reply, 20)->as.real;
    return PILOT_OK;
}
int pilot_device_read(pilot_client *client, pilot_device_read_result *out, pilot_error *error)
{
    if (!out) return api_error(error, PILOT_INVALID_ARGUMENT);
    memset(out, 0, sizeof(*out));
    pilot_reply *reply = NULL;
    int rc = pilot_call(client, PILOT_METHOD_RTC_GET_DEVICE_PARAM,
                        NULL, 0, &reply, error);
    if (rc != PILOT_OK) return rc;
    return pilot_device_read_decode(reply, true, out, error);
}
void pilot_magnetometer_read_clear(pilot_magnetometer_read_result *out)
{
    if (!out) return;
    pilot_reply_free(out->_private);
    memset(out, 0, sizeof(*out));
}
static int pilot_magnetometer_read_decode(const pilot_reply *reply, bool own, pilot_magnetometer_read_result *out, pilot_error *error)
{
    (void)error;
    memset(out, 0, sizeof(*out));
    out->_private = own ? (void *)reply : NULL;
    out->last_update_ms = pilot_reply_at(reply, 0)->as.i64;
    out->valid = pilot_reply_at(reply, 1)->as.boolean;
    out->x_microtesla = pilot_reply_at(reply, 2)->as.real;
    out->y_microtesla = pilot_reply_at(reply, 3)->as.real;
    out->z_microtesla = pilot_reply_at(reply, 4)->as.real;
    out->magnitude_microtesla = pilot_reply_at(reply, 5)->as.real;
    out->sequence = pilot_reply_at(reply, 6)->as.u64;
    return PILOT_OK;
}
int pilot_magnetometer_read(pilot_client *client, pilot_magnetometer_read_result *out, pilot_error *error)
{
    if (!out) return api_error(error, PILOT_INVALID_ARGUMENT);
    memset(out, 0, sizeof(*out));
    pilot_reply *reply = NULL;
    int rc = pilot_call(client, PILOT_METHOD_RTC_GET_MAGNETOMETER_DATA,
                        NULL, 0, &reply, error);
    if (rc != PILOT_OK) return rc;
    return pilot_magnetometer_read_decode(reply, true, out, error);
}
void pilot_location_read_cell_clear(pilot_location_read_cell_result *out)
{
    if (!out) return;
    pilot_reply_free(out->_private);
    memset(out, 0, sizeof(*out));
}
static int pilot_location_read_cell_decode(const pilot_reply *reply, bool own, pilot_location_read_cell_result *out, pilot_error *error)
{
    (void)error;
    memset(out, 0, sizeof(*out));
    out->_private = own ? (void *)reply : NULL;
    out->state = pilot_reply_at(reply, 0)->as.string;
    out->valid = pilot_reply_at(reply, 1)->as.boolean;
    out->latitude = pilot_reply_at(reply, 2)->as.real;
    out->longitude = pilot_reply_at(reply, 3)->as.real;
    out->radius_m = pilot_reply_at(reply, 4)->as.real;
    out->age_seconds = pilot_reply_at(reply, 5)->as.u32;
    out->detail = pilot_reply_at(reply, 6)->as.string;
    return PILOT_OK;
}
int pilot_location_read_cell(pilot_client *client, pilot_location_read_cell_result *out, pilot_error *error)
{
    if (!out) return api_error(error, PILOT_INVALID_ARGUMENT);
    memset(out, 0, sizeof(*out));
    pilot_reply *reply = NULL;
    int rc = pilot_call(client, PILOT_METHOD_RTC_GET_CELL_LOCATION,
                        NULL, 0, &reply, error);
    if (rc != PILOT_OK) return rc;
    return pilot_location_read_cell_decode(reply, true, out, error);
}
void pilot_gps_read_clear(pilot_gps_read_result *out)
{
    if (!out) return;
    pilot_reply_free(out->_private);
    memset(out, 0, sizeof(*out));
}
static int pilot_gps_read_decode(const pilot_reply *reply, bool own, pilot_gps_read_result *out, pilot_error *error)
{
    (void)error;
    memset(out, 0, sizeof(*out));
    out->_private = own ? (void *)reply : NULL;
    out->status = (const pilot_properties *)pilot_reply_at(reply, 0);
    return PILOT_OK;
}
int pilot_gps_read(pilot_client *client, pilot_gps_read_result *out, pilot_error *error)
{
    if (!out) return api_error(error, PILOT_INVALID_ARGUMENT);
    memset(out, 0, sizeof(*out));
    pilot_reply *reply = NULL;
    int rc = pilot_call(client, PILOT_METHOD_RTC_GET_GPS_STATUS,
                        NULL, 0, &reply, error);
    if (rc != PILOT_OK) return rc;
    return pilot_gps_read_decode(reply, true, out, error);
}
void pilot_control_get_outputs_clear(pilot_control_get_outputs_result *out)
{
    if (!out) return;
    free((void *)out->channels);
    pilot_reply_free(out->_private);
    memset(out, 0, sizeof(*out));
}
static int pilot_control_get_outputs_decode(const pilot_reply *reply, bool own, pilot_control_get_outputs_result *out, pilot_error *error)
{
    (void)error;
    memset(out, 0, sizeof(*out));
    out->_private = own ? (void *)reply : NULL;
    {
        const pilot_value *array = pilot_reply_at(reply, 0);
        pilot_channel_output *items = array->count ? calloc(array->count, sizeof(*items)) : NULL;
        if (array->count && !items) goto no_memory;
        out->channels = items;
        out->channels_count = array->count;
        for (size_t j = 0; j < array->count; ++j) {
            const pilot_value *item = pilot_value_at(array, j);
            items[j].channel = pilot_value_at(item, 0)->as.u32;
            items[j].mode = pilot_value_at(item, 1)->as.u32;
            items[j].value = pilot_value_at(item, 2)->as.i32;
            items[j].enabled = pilot_value_at(item, 3)->as.boolean;
            items[j].digital_supported = pilot_value_at(item, 4)->as.boolean;
        }
    }
    out->debug_active = pilot_reply_at(reply, 1)->as.boolean;
    out->last_remote_rx_ms = pilot_reply_at(reply, 2)->as.i64;
    return PILOT_OK;
no_memory:
    pilot_control_get_outputs_clear(out);
    return api_error(error, PILOT_NO_MEMORY);
}
int pilot_control_get_outputs(pilot_client *client, pilot_control_get_outputs_result *out, pilot_error *error)
{
    if (!out) return api_error(error, PILOT_INVALID_ARGUMENT);
    memset(out, 0, sizeof(*out));
    pilot_reply *reply = NULL;
    int rc = pilot_call(client, PILOT_METHOD_RTC_GET_CHANNEL_OUTPUT_STATUS,
                        NULL, 0, &reply, error);
    if (rc != PILOT_OK) return rc;
    return pilot_control_get_outputs_decode(reply, true, out, error);
}
void pilot_control_debug_begin_clear(pilot_control_debug_begin_result *out)
{
    if (!out) return;
    pilot_reply_free(out->_private);
    memset(out, 0, sizeof(*out));
}
static int pilot_control_debug_begin_decode(const pilot_reply *reply, bool own, pilot_control_debug_begin_result *out, pilot_error *error)
{
    (void)error;
    memset(out, 0, sizeof(*out));
    out->_private = own ? (void *)reply : NULL;
    out->accepted = pilot_reply_at(reply, 0)->as.boolean;
    out->reason = pilot_reply_at(reply, 1)->as.string;
    return PILOT_OK;
}
int pilot_control_debug_begin(pilot_client *client, pilot_control_debug_begin_result *out, pilot_error *error)
{
    if (!out) return api_error(error, PILOT_INVALID_ARGUMENT);
    memset(out, 0, sizeof(*out));
    pilot_reply *reply = NULL;
    int rc = pilot_call(client, PILOT_METHOD_RTC_BEGIN_CHANNEL_DEBUG,
                        NULL, 0, &reply, error);
    if (rc != PILOT_OK) return rc;
    return pilot_control_debug_begin_decode(reply, true, out, error);
}
void pilot_control_debug_set_clear(pilot_control_debug_set_result *out)
{
    if (!out) return;
    pilot_reply_free(out->_private);
    memset(out, 0, sizeof(*out));
}
static int pilot_control_debug_set_decode(const pilot_reply *reply, bool own, pilot_control_debug_set_result *out, pilot_error *error)
{
    (void)error;
    memset(out, 0, sizeof(*out));
    out->_private = own ? (void *)reply : NULL;
    out->accepted = pilot_reply_at(reply, 0)->as.boolean;
    out->reason = pilot_reply_at(reply, 1)->as.string;
    return PILOT_OK;
}
int pilot_control_debug_set(pilot_client *client, uint32_t channel, uint32_t mode, int32_t value, bool enabled, pilot_control_debug_set_result *out, pilot_error *error)
{
    if (!out) return api_error(error, PILOT_INVALID_ARGUMENT);
    memset(out, 0, sizeof(*out));
    pilot_reply *reply = NULL;
    pilot_value args[4] = {0};
    args[0].type = 'u';
    args[0].as.u32 = channel;
    args[1].type = 'u';
    args[1].as.u32 = mode;
    args[2].type = 'i';
    args[2].as.i32 = value;
    args[3].type = 'b';
    args[3].as.boolean = enabled;
    int rc = pilot_call(client, PILOT_METHOD_RTC_SET_CHANNEL_DEBUG,
                        args, 4, &reply, error);
    if (rc != PILOT_OK) return rc;
    return pilot_control_debug_set_decode(reply, true, out, error);
}
void pilot_control_debug_keepalive_clear(pilot_control_debug_keepalive_result *out)
{
    if (!out) return;
    pilot_reply_free(out->_private);
    memset(out, 0, sizeof(*out));
}
static int pilot_control_debug_keepalive_decode(const pilot_reply *reply, bool own, pilot_control_debug_keepalive_result *out, pilot_error *error)
{
    (void)error;
    memset(out, 0, sizeof(*out));
    out->_private = own ? (void *)reply : NULL;
    out->active = pilot_reply_at(reply, 0)->as.boolean;
    return PILOT_OK;
}
int pilot_control_debug_keepalive(pilot_client *client, pilot_control_debug_keepalive_result *out, pilot_error *error)
{
    if (!out) return api_error(error, PILOT_INVALID_ARGUMENT);
    memset(out, 0, sizeof(*out));
    pilot_reply *reply = NULL;
    int rc = pilot_call(client, PILOT_METHOD_RTC_CHANNEL_DEBUG_KEEP_ALIVE,
                        NULL, 0, &reply, error);
    if (rc != PILOT_OK) return rc;
    return pilot_control_debug_keepalive_decode(reply, true, out, error);
}
void pilot_control_debug_end_clear(pilot_control_debug_end_result *out)
{
    if (!out) return;
    pilot_reply_free(out->_private);
    memset(out, 0, sizeof(*out));
}
static int pilot_control_debug_end_decode(const pilot_reply *reply, bool own, pilot_control_debug_end_result *out, pilot_error *error)
{
    (void)error;
    memset(out, 0, sizeof(*out));
    out->_private = own ? (void *)reply : NULL;
    out->ended = pilot_reply_at(reply, 0)->as.boolean;
    return PILOT_OK;
}
int pilot_control_debug_end(pilot_client *client, pilot_control_debug_end_result *out, pilot_error *error)
{
    if (!out) return api_error(error, PILOT_INVALID_ARGUMENT);
    memset(out, 0, sizeof(*out));
    pilot_reply *reply = NULL;
    int rc = pilot_call(client, PILOT_METHOD_RTC_END_CHANNEL_DEBUG,
                        NULL, 0, &reply, error);
    if (rc != PILOT_OK) return rc;
    return pilot_control_debug_end_decode(reply, true, out, error);
}
void pilot_media_read_clear(pilot_media_read_result *out)
{
    if (!out) return;
    pilot_reply_free(out->_private);
    memset(out, 0, sizeof(*out));
}
static int pilot_media_read_decode(const pilot_reply *reply, bool own, pilot_media_read_result *out, pilot_error *error)
{
    (void)error;
    memset(out, 0, sizeof(*out));
    out->_private = own ? (void *)reply : NULL;
    out->status = (const pilot_properties *)pilot_reply_at(reply, 0);
    return PILOT_OK;
}
int pilot_media_read(pilot_client *client, pilot_media_read_result *out, pilot_error *error)
{
    if (!out) return api_error(error, PILOT_INVALID_ARGUMENT);
    memset(out, 0, sizeof(*out));
    pilot_reply *reply = NULL;
    int rc = pilot_call(client, PILOT_METHOD_RTC_GET_MEDIA_STATUS,
                        NULL, 0, &reply, error);
    if (rc != PILOT_OK) return rc;
    return pilot_media_read_decode(reply, true, out, error);
}
void pilot_audio_read_spectrum_clear(pilot_audio_read_spectrum_result *out)
{
    if (!out) return;
    pilot_reply_free(out->_private);
    memset(out, 0, sizeof(*out));
}
static int pilot_audio_read_spectrum_decode(const pilot_reply *reply, bool own, pilot_audio_read_spectrum_result *out, pilot_error *error)
{
    (void)error;
    memset(out, 0, sizeof(*out));
    out->_private = own ? (void *)reply : NULL;
    out->available = pilot_reply_at(reply, 0)->as.boolean;
    out->sample_rate = pilot_reply_at(reply, 1)->as.u32;
    out->captured_ms = pilot_reply_at(reply, 2)->as.i64;
    out->sequence = pilot_reply_at(reply, 3)->as.u64;
    out->rms_dbfs = pilot_reply_at(reply, 4)->as.real;
    out->peak_dbfs = pilot_reply_at(reply, 5)->as.real;
    out->levels = (pilot_bytes){pilot_reply_at(reply, 6)->bytes, pilot_reply_at(reply, 6)->count};
    return PILOT_OK;
}
int pilot_audio_read_spectrum(pilot_client *client, pilot_audio_read_spectrum_result *out, pilot_error *error)
{
    if (!out) return api_error(error, PILOT_INVALID_ARGUMENT);
    memset(out, 0, sizeof(*out));
    pilot_reply *reply = NULL;
    int rc = pilot_call(client, PILOT_METHOD_RTC_GET_AUDIO_SPECTRUM,
                        NULL, 0, &reply, error);
    if (rc != PILOT_OK) return rc;
    return pilot_audio_read_spectrum_decode(reply, true, out, error);
}
void pilot_audio_get_volume_clear(pilot_audio_get_volume_result *out)
{
    if (!out) return;
    pilot_reply_free(out->_private);
    memset(out, 0, sizeof(*out));
}
static int pilot_audio_get_volume_decode(const pilot_reply *reply, bool own, pilot_audio_get_volume_result *out, pilot_error *error)
{
    (void)error;
    memset(out, 0, sizeof(*out));
    out->_private = own ? (void *)reply : NULL;
    out->available = pilot_reply_at(reply, 0)->as.boolean;
    out->input_volume = pilot_reply_at(reply, 1)->as.u32;
    out->output_volume = pilot_reply_at(reply, 2)->as.u32;
    return PILOT_OK;
}
int pilot_audio_get_volume(pilot_client *client, pilot_audio_get_volume_result *out, pilot_error *error)
{
    if (!out) return api_error(error, PILOT_INVALID_ARGUMENT);
    memset(out, 0, sizeof(*out));
    pilot_reply *reply = NULL;
    int rc = pilot_call(client, PILOT_METHOD_RTC_GET_AUDIO_VOLUME,
                        NULL, 0, &reply, error);
    if (rc != PILOT_OK) return rc;
    return pilot_audio_get_volume_decode(reply, true, out, error);
}
void pilot_audio_set_volume_clear(pilot_audio_set_volume_result *out)
{
    if (!out) return;
    pilot_reply_free(out->_private);
    memset(out, 0, sizeof(*out));
}
static int pilot_audio_set_volume_decode(const pilot_reply *reply, bool own, pilot_audio_set_volume_result *out, pilot_error *error)
{
    (void)error;
    memset(out, 0, sizeof(*out));
    out->_private = own ? (void *)reply : NULL;
    out->accepted = pilot_reply_at(reply, 0)->as.boolean;
    out->actual_volume = pilot_reply_at(reply, 1)->as.u32;
    out->reason = pilot_reply_at(reply, 2)->as.string;
    return PILOT_OK;
}
int pilot_audio_set_volume(pilot_client *client, const char * target, uint32_t volume, pilot_audio_set_volume_result *out, pilot_error *error)
{
    if (!out) return api_error(error, PILOT_INVALID_ARGUMENT);
    memset(out, 0, sizeof(*out));
    pilot_reply *reply = NULL;
    pilot_value args[2] = {0};
    args[0].type = 's';
    args[0].as.string = target;
    args[1].type = 'u';
    args[1].as.u32 = volume;
    int rc = pilot_call(client, PILOT_METHOD_RTC_SET_AUDIO_VOLUME,
                        args, 2, &reply, error);
    if (rc != PILOT_OK) return rc;
    return pilot_audio_set_volume_decode(reply, true, out, error);
}
void pilot_camera_capture_preview_clear(pilot_camera_capture_preview_result *out)
{
    if (!out) return;
    pilot_reply_free(out->_private);
    memset(out, 0, sizeof(*out));
}
static int pilot_camera_capture_preview_decode(const pilot_reply *reply, bool own, pilot_camera_capture_preview_result *out, pilot_error *error)
{
    (void)error;
    memset(out, 0, sizeof(*out));
    out->_private = own ? (void *)reply : NULL;
    out->success = pilot_reply_at(reply, 0)->as.boolean;
    out->width = pilot_reply_at(reply, 1)->as.u32;
    out->height = pilot_reply_at(reply, 2)->as.u32;
    out->stride_bytes = pilot_reply_at(reply, 3)->as.u32;
    out->captured_ms = pilot_reply_at(reply, 4)->as.i64;
    out->rgb565 = (pilot_bytes){pilot_reply_at(reply, 5)->bytes, pilot_reply_at(reply, 5)->count};
    out->reason = pilot_reply_at(reply, 6)->as.string;
    return PILOT_OK;
}
int pilot_camera_capture_preview(pilot_client *client, pilot_camera_capture_preview_result *out, pilot_error *error)
{
    if (!out) return api_error(error, PILOT_INVALID_ARGUMENT);
    memset(out, 0, sizeof(*out));
    pilot_reply *reply = NULL;
    int rc = pilot_call(client, PILOT_METHOD_RTC_CAPTURE_CAMERA_PREVIEW,
                        NULL, 0, &reply, error);
    if (rc != PILOT_OK) return rc;
    return pilot_camera_capture_preview_decode(reply, true, out, error);
}
void pilot_connection_get_stats_clear(pilot_connection_get_stats_result *out)
{
    if (!out) return;
    free((void *)out->endpoints);
    pilot_reply_free(out->_private);
    memset(out, 0, sizeof(*out));
}
static int pilot_connection_get_stats_decode(const pilot_reply *reply, bool own, pilot_connection_get_stats_result *out, pilot_error *error)
{
    (void)error;
    memset(out, 0, sizeof(*out));
    out->_private = own ? (void *)reply : NULL;
    {
        const pilot_value *array = pilot_reply_at(reply, 0);
        pilot_transport_stats *items = array->count ? calloc(array->count, sizeof(*items)) : NULL;
        if (array->count && !items) goto no_memory;
        out->endpoints = items;
        out->endpoints_count = array->count;
        for (size_t j = 0; j < array->count; ++j) {
            const pilot_value *item = pilot_value_at(array, j);
            items[j].type = pilot_value_at(item, 0)->as.string;
            items[j].connected = pilot_value_at(item, 1)->as.boolean;
            items[j].active = pilot_value_at(item, 2)->as.boolean;
            items[j].subscribers = pilot_value_at(item, 3)->as.i32;
            items[j].rtt_us = pilot_value_at(item, 4)->as.u64;
            items[j].bytes_sent = pilot_value_at(item, 5)->as.u64;
            items[j].bytes_lost = pilot_value_at(item, 6)->as.u64;
            items[j].max_datagram_length = pilot_value_at(item, 7)->as.u32;
        }
    }
    return PILOT_OK;
no_memory:
    pilot_connection_get_stats_clear(out);
    return api_error(error, PILOT_NO_MEMORY);
}
int pilot_connection_get_stats(pilot_client *client, pilot_connection_get_stats_result *out, pilot_error *error)
{
    if (!out) return api_error(error, PILOT_INVALID_ARGUMENT);
    memset(out, 0, sizeof(*out));
    pilot_reply *reply = NULL;
    int rc = pilot_call(client, PILOT_METHOD_RTC_GET_TRANSPORT_STATS,
                        NULL, 0, &reply, error);
    if (rc != PILOT_OK) return rc;
    return pilot_connection_get_stats_decode(reply, true, out, error);
}
void pilot_diagnostics_read_clear(pilot_diagnostics_read_result *out)
{
    if (!out) return;
    pilot_reply_free(out->_private);
    memset(out, 0, sizeof(*out));
}
static int pilot_diagnostics_read_decode(const pilot_reply *reply, bool own, pilot_diagnostics_read_result *out, pilot_error *error)
{
    (void)error;
    memset(out, 0, sizeof(*out));
    out->_private = own ? (void *)reply : NULL;
    out->json = pilot_reply_at(reply, 0)->as.string;
    return PILOT_OK;
}
int pilot_diagnostics_read(pilot_client *client, pilot_diagnostics_read_result *out, pilot_error *error)
{
    if (!out) return api_error(error, PILOT_INVALID_ARGUMENT);
    memset(out, 0, sizeof(*out));
    pilot_reply *reply = NULL;
    int rc = pilot_call(client, PILOT_METHOD_RTC_GET_DIAGNOSTIC_STATS,
                        NULL, 0, &reply, error);
    if (rc != PILOT_OK) return rc;
    return pilot_diagnostics_read_decode(reply, true, out, error);
}
void pilot_network_read_clear(pilot_network_read_result *out)
{
    if (!out) return;
    pilot_reply_free(out->_private);
    memset(out, 0, sizeof(*out));
}
static int pilot_network_read_decode(const pilot_reply *reply, bool own, pilot_network_read_result *out, pilot_error *error)
{
    (void)error;
    memset(out, 0, sizeof(*out));
    out->_private = own ? (void *)reply : NULL;
    out->json = pilot_reply_at(reply, 0)->as.string;
    return PILOT_OK;
}
int pilot_network_read(pilot_client *client, pilot_network_read_result *out, pilot_error *error)
{
    if (!out) return api_error(error, PILOT_INVALID_ARGUMENT);
    memset(out, 0, sizeof(*out));
    pilot_reply *reply = NULL;
    int rc = pilot_call(client, PILOT_METHOD_RTC_GET_NETWORK_DIAGNOSTICS,
                        NULL, 0, &reply, error);
    if (rc != PILOT_OK) return rc;
    return pilot_network_read_decode(reply, true, out, error);
}
void pilot_connection_request_reconnect_clear(pilot_connection_request_reconnect_result *out)
{
    if (!out) return;
    pilot_reply_free(out->_private);
    memset(out, 0, sizeof(*out));
}
static int pilot_connection_request_reconnect_decode(const pilot_reply *reply, bool own, pilot_connection_request_reconnect_result *out, pilot_error *error)
{
    (void)error;
    memset(out, 0, sizeof(*out));
    out->_private = own ? (void *)reply : NULL;
    out->accepted = pilot_reply_at(reply, 0)->as.boolean;
    out->reason = pilot_reply_at(reply, 1)->as.string;
    return PILOT_OK;
}
int pilot_connection_request_reconnect(pilot_client *client, const char * endpoint, pilot_connection_request_reconnect_result *out, pilot_error *error)
{
    if (!out) return api_error(error, PILOT_INVALID_ARGUMENT);
    memset(out, 0, sizeof(*out));
    pilot_reply *reply = NULL;
    pilot_value args[1] = {0};
    args[0].type = 's';
    args[0].as.string = endpoint;
    int rc = pilot_call(client, PILOT_METHOD_RTC_REQUEST_RECONNECT,
                        args, 1, &reply, error);
    if (rc != PILOT_OK) return rc;
    return pilot_connection_request_reconnect_decode(reply, true, out, error);
}
void pilot_selfcheck_read_clear(pilot_selfcheck_read_result *out)
{
    if (!out) return;
    pilot_reply_free(out->_private);
    memset(out, 0, sizeof(*out));
}
static int pilot_selfcheck_read_decode(const pilot_reply *reply, bool own, pilot_selfcheck_read_result *out, pilot_error *error)
{
    (void)error;
    memset(out, 0, sizeof(*out));
    out->_private = own ? (void *)reply : NULL;
    out->json = pilot_reply_at(reply, 0)->as.string;
    return PILOT_OK;
}
int pilot_selfcheck_read(pilot_client *client, pilot_selfcheck_read_result *out, pilot_error *error)
{
    if (!out) return api_error(error, PILOT_INVALID_ARGUMENT);
    memset(out, 0, sizeof(*out));
    pilot_reply *reply = NULL;
    int rc = pilot_call(client, PILOT_METHOD_SELFCHECK_GET_REPORT,
                        NULL, 0, &reply, error);
    if (rc != PILOT_OK) return rc;
    return pilot_selfcheck_read_decode(reply, true, out, error);
}
void pilot_selfcheck_run_clear(pilot_selfcheck_run_result *out)
{
    if (!out) return;
    pilot_reply_free(out->_private);
    memset(out, 0, sizeof(*out));
}
static int pilot_selfcheck_run_decode(const pilot_reply *reply, bool own, pilot_selfcheck_run_result *out, pilot_error *error)
{
    (void)error;
    memset(out, 0, sizeof(*out));
    out->_private = own ? (void *)reply : NULL;
    out->accepted = pilot_reply_at(reply, 0)->as.boolean;
    out->reason = pilot_reply_at(reply, 1)->as.string;
    return PILOT_OK;
}
int pilot_selfcheck_run(pilot_client *client, pilot_selfcheck_run_result *out, pilot_error *error)
{
    if (!out) return api_error(error, PILOT_INVALID_ARGUMENT);
    memset(out, 0, sizeof(*out));
    pilot_reply *reply = NULL;
    int rc = pilot_call(client, PILOT_METHOD_SELFCHECK_RUN_NOW,
                        NULL, 0, &reply, error);
    if (rc != PILOT_OK) return rc;
    return pilot_selfcheck_run_decode(reply, true, out, error);
}
void pilot_network_get_recovery_policy_clear(pilot_network_get_recovery_policy_result *out)
{
    if (!out) return;
    pilot_reply_free(out->_private);
    memset(out, 0, sizeof(*out));
}
static int pilot_network_get_recovery_policy_decode(const pilot_reply *reply, bool own, pilot_network_get_recovery_policy_result *out, pilot_error *error)
{
    (void)error;
    memset(out, 0, sizeof(*out));
    out->_private = own ? (void *)reply : NULL;
    out->ignored = pilot_reply_at(reply, 0)->as.boolean;
    return PILOT_OK;
}
int pilot_network_get_recovery_policy(pilot_client *client, pilot_network_get_recovery_policy_result *out, pilot_error *error)
{
    if (!out) return api_error(error, PILOT_INVALID_ARGUMENT);
    memset(out, 0, sizeof(*out));
    pilot_reply *reply = NULL;
    int rc = pilot_call(client, PILOT_METHOD_SELFCHECK_GET_NETWORK_RECOVERY_POLICY,
                        NULL, 0, &reply, error);
    if (rc != PILOT_OK) return rc;
    return pilot_network_get_recovery_policy_decode(reply, true, out, error);
}
void pilot_network_set_recovery_mode_clear(pilot_network_set_recovery_mode_result *out)
{
    if (!out) return;
    pilot_reply_free(out->_private);
    memset(out, 0, sizeof(*out));
}
static int pilot_network_set_recovery_mode_decode(const pilot_reply *reply, bool own, pilot_network_set_recovery_mode_result *out, pilot_error *error)
{
    (void)error;
    memset(out, 0, sizeof(*out));
    out->_private = own ? (void *)reply : NULL;
    out->ignored = pilot_reply_at(reply, 0)->as.boolean;
    return PILOT_OK;
}
int pilot_network_set_recovery_mode(pilot_client *client, const char * mode, pilot_network_set_recovery_mode_result *out, pilot_error *error)
{
    if (!out) return api_error(error, PILOT_INVALID_ARGUMENT);
    memset(out, 0, sizeof(*out));
    pilot_reply *reply = NULL;
    pilot_value args[1] = {0};
    args[0].type = 's';
    args[0].as.string = mode;
    int rc = pilot_call(client, PILOT_METHOD_SELFCHECK_SET_NETWORK_RECOVERY_MODE,
                        args, 1, &reply, error);
    if (rc != PILOT_OK) return rc;
    return pilot_network_set_recovery_mode_decode(reply, true, out, error);
}
void pilot_fan_get_config_clear(pilot_fan_get_config_result *out)
{
    if (!out) return;
    pilot_reply_free(out->_private);
    memset(out, 0, sizeof(*out));
}
static int pilot_fan_get_config_decode(const pilot_reply *reply, bool own, pilot_fan_get_config_result *out, pilot_error *error)
{
    (void)error;
    memset(out, 0, sizeof(*out));
    out->_private = own ? (void *)reply : NULL;
    out->json = pilot_reply_at(reply, 0)->as.string;
    return PILOT_OK;
}
int pilot_fan_get_config(pilot_client *client, pilot_fan_get_config_result *out, pilot_error *error)
{
    if (!out) return api_error(error, PILOT_INVALID_ARGUMENT);
    memset(out, 0, sizeof(*out));
    pilot_reply *reply = NULL;
    int rc = pilot_call(client, PILOT_METHOD_FAN_GET_CONFIG,
                        NULL, 0, &reply, error);
    if (rc != PILOT_OK) return rc;
    return pilot_fan_get_config_decode(reply, true, out, error);
}
void pilot_fan_set_config_clear(pilot_fan_set_config_result *out)
{
    if (!out) return;
    pilot_reply_free(out->_private);
    memset(out, 0, sizeof(*out));
}
static int pilot_fan_set_config_decode(const pilot_reply *reply, bool own, pilot_fan_set_config_result *out, pilot_error *error)
{
    (void)error;
    memset(out, 0, sizeof(*out));
    out->_private = own ? (void *)reply : NULL;
    out->json = pilot_reply_at(reply, 0)->as.string;
    return PILOT_OK;
}
int pilot_fan_set_config(pilot_client *client, const char * request, pilot_fan_set_config_result *out, pilot_error *error)
{
    if (!out) return api_error(error, PILOT_INVALID_ARGUMENT);
    memset(out, 0, sizeof(*out));
    pilot_reply *reply = NULL;
    pilot_value args[1] = {0};
    args[0].type = 's';
    args[0].as.string = request;
    int rc = pilot_call(client, PILOT_METHOD_FAN_SET_CONFIG,
                        args, 1, &reply, error);
    if (rc != PILOT_OK) return rc;
    return pilot_fan_set_config_decode(reply, true, out, error);
}
static void pilot_watch_control_clear(pilot_control_event *out)
{
    if (!out) return;
    free((void *)out->signals);
    pilot_reply_free(out->_private);
    memset(out, 0, sizeof(*out));
}
static int pilot_watch_control_decode(const pilot_reply *reply, bool own, pilot_control_event *out, pilot_error *error)
{
    (void)error;
    memset(out, 0, sizeof(*out));
    out->_private = own ? (void *)reply : NULL;
    {
        const pilot_value *array = pilot_reply_at(reply, 0);
        int32_t *items = array->count ? calloc(array->count, sizeof(*items)) : NULL;
        if (array->count && !items) goto no_memory;
        out->signals = items;
        out->signals_count = array->count;
        for (size_t j = 0; j < array->count; ++j) {
            const pilot_value *item = pilot_value_at(array, j);
            items[j] = item->as.i32;
        }
    }
    out->last_rx_ms = pilot_reply_at(reply, 1)->as.i64;
    return PILOT_OK;
no_memory:
    pilot_watch_control_clear(out);
    return api_error(error, PILOT_NO_MEMORY);
}
typedef struct { pilot_control_callback callback; void *userdata; } pilot_watch_control_context;
static int pilot_watch_control_dispatch(unsigned id, const pilot_reply *reply, void *context, pilot_error *error)
{
    (void)id;
    pilot_watch_control_context *ctx = context;
    pilot_control_event event;
    int rc = pilot_watch_control_decode(reply, false, &event, error);
    if (rc != PILOT_OK) return rc;
    ctx->callback(&event, ctx->userdata);
    pilot_watch_control_clear(&event);
    return PILOT_OK;
}
int pilot_watch_control(pilot_client *client, pilot_control_callback callback, void *userdata, pilot_error *error)
{
    unsigned id = PILOT_SIGNAL_RTC_CONTROL_SIGNALS_CHANGED;
    if (!callback) return pilot_watch_install(client, id, NULL, NULL, error);
    pilot_watch_control_context *ctx = malloc(sizeof(*ctx));
    if (!ctx) return api_error(error, PILOT_NO_MEMORY);
    ctx->callback = callback; ctx->userdata = userdata;
    return pilot_watch_install(client, id, pilot_watch_control_dispatch, ctx, error);
}
static void pilot_watch_imu_clear(pilot_imu_event *out)
{
    if (!out) return;
    pilot_reply_free(out->_private);
    memset(out, 0, sizeof(*out));
}
static int pilot_watch_imu_decode(const pilot_reply *reply, bool own, pilot_imu_event *out, pilot_error *error)
{
    (void)error;
    memset(out, 0, sizeof(*out));
    out->_private = own ? (void *)reply : NULL;
    out->last_update_ms = pilot_reply_at(reply, 0)->as.i64;
    out->has_imu = pilot_reply_at(reply, 1)->as.boolean;
    out->gyro_x = pilot_reply_at(reply, 2)->as.real;
    out->gyro_y = pilot_reply_at(reply, 3)->as.real;
    out->gyro_z = pilot_reply_at(reply, 4)->as.real;
    out->accel_x = pilot_reply_at(reply, 5)->as.real;
    out->accel_y = pilot_reply_at(reply, 6)->as.real;
    out->accel_z = pilot_reply_at(reply, 7)->as.real;
    return PILOT_OK;
}
typedef struct { pilot_imu_callback callback; void *userdata; } pilot_watch_imu_context;
static int pilot_watch_imu_dispatch(unsigned id, const pilot_reply *reply, void *context, pilot_error *error)
{
    (void)id;
    pilot_watch_imu_context *ctx = context;
    pilot_imu_event event;
    int rc = pilot_watch_imu_decode(reply, false, &event, error);
    if (rc != PILOT_OK) return rc;
    ctx->callback(&event, ctx->userdata);
    pilot_watch_imu_clear(&event);
    return PILOT_OK;
}
int pilot_watch_imu(pilot_client *client, pilot_imu_callback callback, void *userdata, pilot_error *error)
{
    unsigned id = PILOT_SIGNAL_RTC_IMU_DATA_CHANGED;
    if (!callback) return pilot_watch_install(client, id, NULL, NULL, error);
    pilot_watch_imu_context *ctx = malloc(sizeof(*ctx));
    if (!ctx) return api_error(error, PILOT_NO_MEMORY);
    ctx->callback = callback; ctx->userdata = userdata;
    return pilot_watch_install(client, id, pilot_watch_imu_dispatch, ctx, error);
}
static void pilot_watch_magnetometer_clear(pilot_magnetometer_event *out)
{
    if (!out) return;
    pilot_reply_free(out->_private);
    memset(out, 0, sizeof(*out));
}
static int pilot_watch_magnetometer_decode(const pilot_reply *reply, bool own, pilot_magnetometer_event *out, pilot_error *error)
{
    (void)error;
    memset(out, 0, sizeof(*out));
    out->_private = own ? (void *)reply : NULL;
    out->last_update_ms = pilot_reply_at(reply, 0)->as.i64;
    out->valid = pilot_reply_at(reply, 1)->as.boolean;
    out->x_microtesla = pilot_reply_at(reply, 2)->as.real;
    out->y_microtesla = pilot_reply_at(reply, 3)->as.real;
    out->z_microtesla = pilot_reply_at(reply, 4)->as.real;
    out->magnitude_microtesla = pilot_reply_at(reply, 5)->as.real;
    out->sequence = pilot_reply_at(reply, 6)->as.u64;
    return PILOT_OK;
}
typedef struct { pilot_magnetometer_callback callback; void *userdata; } pilot_watch_magnetometer_context;
static int pilot_watch_magnetometer_dispatch(unsigned id, const pilot_reply *reply, void *context, pilot_error *error)
{
    (void)id;
    pilot_watch_magnetometer_context *ctx = context;
    pilot_magnetometer_event event;
    int rc = pilot_watch_magnetometer_decode(reply, false, &event, error);
    if (rc != PILOT_OK) return rc;
    ctx->callback(&event, ctx->userdata);
    pilot_watch_magnetometer_clear(&event);
    return PILOT_OK;
}
int pilot_watch_magnetometer(pilot_client *client, pilot_magnetometer_callback callback, void *userdata, pilot_error *error)
{
    unsigned id = PILOT_SIGNAL_RTC_MAGNETOMETER_DATA_CHANGED;
    if (!callback) return pilot_watch_install(client, id, NULL, NULL, error);
    pilot_watch_magnetometer_context *ctx = malloc(sizeof(*ctx));
    if (!ctx) return api_error(error, PILOT_NO_MEMORY);
    ctx->callback = callback; ctx->userdata = userdata;
    return pilot_watch_install(client, id, pilot_watch_magnetometer_dispatch, ctx, error);
}
static void pilot_watch_connection_clear(pilot_connection_event *out)
{
    if (!out) return;
    pilot_reply_free(out->_private);
    memset(out, 0, sizeof(*out));
}
static int pilot_watch_connection_decode(const pilot_reply *reply, bool own, pilot_connection_event *out, pilot_error *error)
{
    (void)error;
    memset(out, 0, sizeof(*out));
    out->_private = own ? (void *)reply : NULL;
    out->type = pilot_reply_at(reply, 0)->as.string;
    out->connected = pilot_reply_at(reply, 1)->as.boolean;
    out->subscribe_count = pilot_reply_at(reply, 2)->as.i32;
    out->is_active = pilot_reply_at(reply, 3)->as.boolean;
    return PILOT_OK;
}
typedef struct { pilot_connection_callback callback; void *userdata; } pilot_watch_connection_context;
static int pilot_watch_connection_dispatch(unsigned id, const pilot_reply *reply, void *context, pilot_error *error)
{
    (void)id;
    pilot_watch_connection_context *ctx = context;
    pilot_connection_event event;
    int rc = pilot_watch_connection_decode(reply, false, &event, error);
    if (rc != PILOT_OK) return rc;
    ctx->callback(&event, ctx->userdata);
    pilot_watch_connection_clear(&event);
    return PILOT_OK;
}
int pilot_watch_connection(pilot_client *client, pilot_connection_callback callback, void *userdata, pilot_error *error)
{
    unsigned id = PILOT_SIGNAL_RTC_ENDPOINT_STATE_CHANGED;
    if (!callback) return pilot_watch_install(client, id, NULL, NULL, error);
    pilot_watch_connection_context *ctx = malloc(sizeof(*ctx));
    if (!ctx) return api_error(error, PILOT_NO_MEMORY);
    ctx->callback = callback; ctx->userdata = userdata;
    return pilot_watch_install(client, id, pilot_watch_connection_dispatch, ctx, error);
}
static void pilot_watch_network_clear(pilot_network_event *out)
{
    if (!out) return;
    pilot_reply_free(out->_private);
    memset(out, 0, sizeof(*out));
}
static int pilot_watch_network_decode(const pilot_reply *reply, bool own, pilot_network_event *out, pilot_error *error)
{
    (void)error;
    memset(out, 0, sizeof(*out));
    out->_private = own ? (void *)reply : NULL;
    out->json = pilot_reply_at(reply, 0)->as.string;
    return PILOT_OK;
}
typedef struct { pilot_network_callback callback; void *userdata; } pilot_watch_network_context;
static int pilot_watch_network_dispatch(unsigned id, const pilot_reply *reply, void *context, pilot_error *error)
{
    (void)id;
    pilot_watch_network_context *ctx = context;
    pilot_network_event event;
    int rc = pilot_watch_network_decode(reply, false, &event, error);
    if (rc != PILOT_OK) return rc;
    ctx->callback(&event, ctx->userdata);
    pilot_watch_network_clear(&event);
    return PILOT_OK;
}
int pilot_watch_network(pilot_client *client, pilot_network_callback callback, void *userdata, pilot_error *error)
{
    unsigned id = PILOT_SIGNAL_RTC_NETWORK_DIAGNOSTICS_CHANGED;
    if (!callback) return pilot_watch_install(client, id, NULL, NULL, error);
    pilot_watch_network_context *ctx = malloc(sizeof(*ctx));
    if (!ctx) return api_error(error, PILOT_NO_MEMORY);
    ctx->callback = callback; ctx->userdata = userdata;
    return pilot_watch_install(client, id, pilot_watch_network_dispatch, ctx, error);
}
static void pilot_watch_selfcheck_clear(pilot_selfcheck_event *out)
{
    if (!out) return;
    pilot_reply_free(out->_private);
    memset(out, 0, sizeof(*out));
}
static int pilot_watch_selfcheck_decode(const pilot_reply *reply, bool own, pilot_selfcheck_event *out, pilot_error *error)
{
    (void)error;
    memset(out, 0, sizeof(*out));
    out->_private = own ? (void *)reply : NULL;
    out->json = pilot_reply_at(reply, 0)->as.string;
    return PILOT_OK;
}
typedef struct { pilot_selfcheck_callback callback; void *userdata; } pilot_watch_selfcheck_context;
static int pilot_watch_selfcheck_dispatch(unsigned id, const pilot_reply *reply, void *context, pilot_error *error)
{
    (void)id;
    pilot_watch_selfcheck_context *ctx = context;
    pilot_selfcheck_event event;
    int rc = pilot_watch_selfcheck_decode(reply, false, &event, error);
    if (rc != PILOT_OK) return rc;
    ctx->callback(&event, ctx->userdata);
    pilot_watch_selfcheck_clear(&event);
    return PILOT_OK;
}
int pilot_watch_selfcheck(pilot_client *client, pilot_selfcheck_callback callback, void *userdata, pilot_error *error)
{
    unsigned id = PILOT_SIGNAL_SELFCHECK_REPORT_CHANGED;
    if (!callback) return pilot_watch_install(client, id, NULL, NULL, error);
    pilot_watch_selfcheck_context *ctx = malloc(sizeof(*ctx));
    if (!ctx) return api_error(error, PILOT_NO_MEMORY);
    ctx->callback = callback; ctx->userdata = userdata;
    return pilot_watch_install(client, id, pilot_watch_selfcheck_dispatch, ctx, error);
}
static void pilot_watch_cellular_clear(pilot_cellular_event *out)
{
    if (!out) return;
    pilot_reply_free(out->_private);
    memset(out, 0, sizeof(*out));
}
static int pilot_watch_cellular_decode(const pilot_reply *reply, bool own, pilot_cellular_event *out, pilot_error *error)
{
    (void)error;
    memset(out, 0, sizeof(*out));
    out->_private = own ? (void *)reply : NULL;
    out->json = pilot_reply_at(reply, 0)->as.string;
    return PILOT_OK;
}
typedef struct { pilot_cellular_callback callback; void *userdata; } pilot_watch_cellular_context;
static int pilot_watch_cellular_dispatch(unsigned id, const pilot_reply *reply, void *context, pilot_error *error)
{
    (void)id;
    pilot_watch_cellular_context *ctx = context;
    pilot_cellular_event event;
    int rc = pilot_watch_cellular_decode(reply, false, &event, error);
    if (rc != PILOT_OK) return rc;
    ctx->callback(&event, ctx->userdata);
    pilot_watch_cellular_clear(&event);
    return PILOT_OK;
}
int pilot_watch_cellular(pilot_client *client, pilot_cellular_callback callback, void *userdata, pilot_error *error)
{
    unsigned id = PILOT_SIGNAL_MODEM_CELL_INFO_CHANGED;
    if (!callback) return pilot_watch_install(client, id, NULL, NULL, error);
    pilot_watch_cellular_context *ctx = malloc(sizeof(*ctx));
    if (!ctx) return api_error(error, PILOT_NO_MEMORY);
    ctx->callback = callback; ctx->userdata = userdata;
    return pilot_watch_install(client, id, pilot_watch_cellular_dispatch, ctx, error);
}
