/* Generated by scripts/generate.py. Do not edit. */
#include "pilot/api.h"
#include <string.h>
const pilot_service pilot_services[] = {
    {"tech.andless.RealTimeComm", "/tech/andless/RealTimeComm/Status", "tech.andless.RealTimeComm.Status1"},
    {"tech.andless.SelfCheck", "/tech/andless/SelfCheck/Report", "tech.andless.SelfCheck.Report1"},
    {"tech.andless.Fan", "/tech/andless/Fan", "tech.andless.Fan.Config1"},
    {"tech.andless.Modem", "/tech/andless/Modem", "tech.andless.Modem.Status1"},
};
const size_t pilot_service_count = sizeof(pilot_services) / sizeof(pilot_services[0]);
const pilot_method pilot_methods[] = {
    {PILOT_SERVICE_RTC, "BatteryCommand", "s", "s"},
    {PILOT_SERVICE_RTC, "GetActiveEndpoint", "", "i"},
    {PILOT_SERVICE_RTC, "GetCloudStatus", "", "sbsqib"},
    {PILOT_SERVICE_RTC, "GetP2PStatus", "", "sbsqib"},
    {PILOT_SERVICE_RTC, "GetAllStatus", "", "a(sbsqib)i"},
    {PILOT_SERVICE_RTC, "GetControlSignals", "", "aix"},
    {PILOT_SERVICE_RTC, "SetChannelOutput", "ii", "b"},
    {PILOT_SERVICE_RTC, "GetImuData", "", "xbdddddd"},
    {PILOT_SERVICE_RTC, "GetDeviceParam", "", "xbddddddddddidibdddid"},
    {PILOT_SERVICE_RTC, "GetMagnetometerData", "", "xbddddt"},
    {PILOT_SERVICE_RTC, "GetCellLocation", "", "sbdddus"},
    {PILOT_SERVICE_RTC, "GetGpsStatus", "", "a{sv}"},
    {PILOT_SERVICE_RTC, "GetChannelOutputStatus", "", "a(uuibb)bx"},
    {PILOT_SERVICE_RTC, "BeginChannelDebug", "", "bs"},
    {PILOT_SERVICE_RTC, "SetChannelDebug", "uuib", "bs"},
    {PILOT_SERVICE_RTC, "ChannelDebugKeepAlive", "", "b"},
    {PILOT_SERVICE_RTC, "EndChannelDebug", "", "b"},
    {PILOT_SERVICE_RTC, "GetMediaStatus", "", "a{sv}"},
    {PILOT_SERVICE_RTC, "GetAudioSpectrum", "", "buxtdday"},
    {PILOT_SERVICE_RTC, "GetAudioVolume", "", "buu"},
    {PILOT_SERVICE_RTC, "SetAudioVolume", "su", "bus"},
    {PILOT_SERVICE_RTC, "CaptureCameraPreview", "", "buuuxays"},
    {PILOT_SERVICE_RTC, "GetTransportStats", "", "a(sbbitttu)"},
    {PILOT_SERVICE_RTC, "GetDiagnosticStats", "", "s"},
    {PILOT_SERVICE_RTC, "GetNetworkDiagnostics", "", "s"},
    {PILOT_SERVICE_RTC, "RequestReconnect", "s", "bs"},
    {PILOT_SERVICE_SELFCHECK, "GetReport", "", "s"},
    {PILOT_SERVICE_SELFCHECK, "RunNow", "", "bs"},
    {PILOT_SERVICE_SELFCHECK, "GetNetworkRecoveryPolicy", "", "b"},
    {PILOT_SERVICE_SELFCHECK, "SetNetworkRecoveryMode", "s", "b"},
    {PILOT_SERVICE_FAN, "GetConfig", "", "s"},
    {PILOT_SERVICE_FAN, "SetConfig", "s", "s"},
};
const size_t pilot_method_count = sizeof(pilot_methods) / sizeof(pilot_methods[0]);
const pilot_signal pilot_signals[] = {
    {PILOT_SERVICE_RTC, "ControlSignalsChanged", "aix"},
    {PILOT_SERVICE_RTC, "ImuDataChanged", "xbdddddd"},
    {PILOT_SERVICE_RTC, "MagnetometerDataChanged", "xbddddt"},
    {PILOT_SERVICE_RTC, "EndpointStateChanged", "sbib"},
    {PILOT_SERVICE_RTC, "NetworkDiagnosticsChanged", "s"},
    {PILOT_SERVICE_SELFCHECK, "ReportChanged", "s"},
    {PILOT_SERVICE_MODEM, "CellInfoChanged", "s"},
};
const size_t pilot_signal_count = sizeof(pilot_signals) / sizeof(pilot_signals[0]);
int pilot_rtc_battery_command(pilot_client *client, const char * request, pilot_rtc_battery_command_result *out, pilot_error *error)
{
    if (!out) {
        if (error) { memset(error, 0, sizeof(*error)); error->code = PILOT_INVALID_ARGUMENT;
            strcpy(error->message, "Missing output argument"); }
        return PILOT_INVALID_ARGUMENT;
    }
    memset(out, 0, sizeof(*out));
    pilot_value args[1] = {0};
    args[0].type = 's';
    args[0].as.string = request;
    int rc = pilot_call(client, PILOT_METHOD_RTC_BATTERY_COMMAND,
                        args, 1, &out->_reply, error);
    if (rc != PILOT_OK) return rc;
    out->response = pilot_reply_at(out->_reply, 0)->as.string;
    return PILOT_OK;
}
void pilot_rtc_battery_command_clear(pilot_rtc_battery_command_result *out)
{
    if (out) { pilot_reply_free(out->_reply); memset(out, 0, sizeof(*out)); }
}
int pilot_rtc_get_active_endpoint(pilot_client *client, pilot_rtc_get_active_endpoint_result *out, pilot_error *error)
{
    if (!out) {
        if (error) { memset(error, 0, sizeof(*error)); error->code = PILOT_INVALID_ARGUMENT;
            strcpy(error->message, "Missing output argument"); }
        return PILOT_INVALID_ARGUMENT;
    }
    memset(out, 0, sizeof(*out));
    int rc = pilot_call(client, PILOT_METHOD_RTC_GET_ACTIVE_ENDPOINT,
                        NULL, 0, &out->_reply, error);
    if (rc != PILOT_OK) return rc;
    out->index = pilot_reply_at(out->_reply, 0)->as.i32;
    return PILOT_OK;
}
void pilot_rtc_get_active_endpoint_clear(pilot_rtc_get_active_endpoint_result *out)
{
    if (out) { pilot_reply_free(out->_reply); memset(out, 0, sizeof(*out)); }
}
int pilot_rtc_get_cloud_status(pilot_client *client, pilot_rtc_get_cloud_status_result *out, pilot_error *error)
{
    if (!out) {
        if (error) { memset(error, 0, sizeof(*error)); error->code = PILOT_INVALID_ARGUMENT;
            strcpy(error->message, "Missing output argument"); }
        return PILOT_INVALID_ARGUMENT;
    }
    memset(out, 0, sizeof(*out));
    int rc = pilot_call(client, PILOT_METHOD_RTC_GET_CLOUD_STATUS,
                        NULL, 0, &out->_reply, error);
    if (rc != PILOT_OK) return rc;
    out->type = pilot_reply_at(out->_reply, 0)->as.string;
    out->connected = pilot_reply_at(out->_reply, 1)->as.boolean;
    out->ip = pilot_reply_at(out->_reply, 2)->as.string;
    out->port = pilot_reply_at(out->_reply, 3)->as.u16;
    out->subscribe_count = pilot_reply_at(out->_reply, 4)->as.i32;
    out->is_active = pilot_reply_at(out->_reply, 5)->as.boolean;
    return PILOT_OK;
}
void pilot_rtc_get_cloud_status_clear(pilot_rtc_get_cloud_status_result *out)
{
    if (out) { pilot_reply_free(out->_reply); memset(out, 0, sizeof(*out)); }
}
int pilot_rtc_get_p2p_status(pilot_client *client, pilot_rtc_get_p2p_status_result *out, pilot_error *error)
{
    if (!out) {
        if (error) { memset(error, 0, sizeof(*error)); error->code = PILOT_INVALID_ARGUMENT;
            strcpy(error->message, "Missing output argument"); }
        return PILOT_INVALID_ARGUMENT;
    }
    memset(out, 0, sizeof(*out));
    int rc = pilot_call(client, PILOT_METHOD_RTC_GET_P2P_STATUS,
                        NULL, 0, &out->_reply, error);
    if (rc != PILOT_OK) return rc;
    out->type = pilot_reply_at(out->_reply, 0)->as.string;
    out->connected = pilot_reply_at(out->_reply, 1)->as.boolean;
    out->ip = pilot_reply_at(out->_reply, 2)->as.string;
    out->port = pilot_reply_at(out->_reply, 3)->as.u16;
    out->subscribe_count = pilot_reply_at(out->_reply, 4)->as.i32;
    out->is_active = pilot_reply_at(out->_reply, 5)->as.boolean;
    return PILOT_OK;
}
void pilot_rtc_get_p2p_status_clear(pilot_rtc_get_p2p_status_result *out)
{
    if (out) { pilot_reply_free(out->_reply); memset(out, 0, sizeof(*out)); }
}
int pilot_rtc_get_all_status(pilot_client *client, pilot_rtc_get_all_status_result *out, pilot_error *error)
{
    if (!out) {
        if (error) { memset(error, 0, sizeof(*error)); error->code = PILOT_INVALID_ARGUMENT;
            strcpy(error->message, "Missing output argument"); }
        return PILOT_INVALID_ARGUMENT;
    }
    memset(out, 0, sizeof(*out));
    int rc = pilot_call(client, PILOT_METHOD_RTC_GET_ALL_STATUS,
                        NULL, 0, &out->_reply, error);
    if (rc != PILOT_OK) return rc;
    out->endpoints = pilot_reply_at(out->_reply, 0);
    out->active_index = pilot_reply_at(out->_reply, 1)->as.i32;
    return PILOT_OK;
}
void pilot_rtc_get_all_status_clear(pilot_rtc_get_all_status_result *out)
{
    if (out) { pilot_reply_free(out->_reply); memset(out, 0, sizeof(*out)); }
}
int pilot_rtc_get_control_signals(pilot_client *client, pilot_rtc_get_control_signals_result *out, pilot_error *error)
{
    if (!out) {
        if (error) { memset(error, 0, sizeof(*error)); error->code = PILOT_INVALID_ARGUMENT;
            strcpy(error->message, "Missing output argument"); }
        return PILOT_INVALID_ARGUMENT;
    }
    memset(out, 0, sizeof(*out));
    int rc = pilot_call(client, PILOT_METHOD_RTC_GET_CONTROL_SIGNALS,
                        NULL, 0, &out->_reply, error);
    if (rc != PILOT_OK) return rc;
    out->signals = pilot_reply_at(out->_reply, 0);
    out->last_rx_ms = pilot_reply_at(out->_reply, 1)->as.i64;
    return PILOT_OK;
}
void pilot_rtc_get_control_signals_clear(pilot_rtc_get_control_signals_result *out)
{
    if (out) { pilot_reply_free(out->_reply); memset(out, 0, sizeof(*out)); }
}
int pilot_rtc_set_channel_output(pilot_client *client, int32_t channel, int32_t value, pilot_rtc_set_channel_output_result *out, pilot_error *error)
{
    if (!out) {
        if (error) { memset(error, 0, sizeof(*error)); error->code = PILOT_INVALID_ARGUMENT;
            strcpy(error->message, "Missing output argument"); }
        return PILOT_INVALID_ARGUMENT;
    }
    memset(out, 0, sizeof(*out));
    pilot_value args[2] = {0};
    args[0].type = 'i';
    args[0].as.i32 = channel;
    args[1].type = 'i';
    args[1].as.i32 = value;
    int rc = pilot_call(client, PILOT_METHOD_RTC_SET_CHANNEL_OUTPUT,
                        args, 2, &out->_reply, error);
    if (rc != PILOT_OK) return rc;
    out->applied = pilot_reply_at(out->_reply, 0)->as.boolean;
    return PILOT_OK;
}
void pilot_rtc_set_channel_output_clear(pilot_rtc_set_channel_output_result *out)
{
    if (out) { pilot_reply_free(out->_reply); memset(out, 0, sizeof(*out)); }
}
int pilot_rtc_get_imu_data(pilot_client *client, pilot_rtc_get_imu_data_result *out, pilot_error *error)
{
    if (!out) {
        if (error) { memset(error, 0, sizeof(*error)); error->code = PILOT_INVALID_ARGUMENT;
            strcpy(error->message, "Missing output argument"); }
        return PILOT_INVALID_ARGUMENT;
    }
    memset(out, 0, sizeof(*out));
    int rc = pilot_call(client, PILOT_METHOD_RTC_GET_IMU_DATA,
                        NULL, 0, &out->_reply, error);
    if (rc != PILOT_OK) return rc;
    out->last_sample_ms = pilot_reply_at(out->_reply, 0)->as.i64;
    out->valid = pilot_reply_at(out->_reply, 1)->as.boolean;
    out->gyro_x = pilot_reply_at(out->_reply, 2)->as.real;
    out->gyro_y = pilot_reply_at(out->_reply, 3)->as.real;
    out->gyro_z = pilot_reply_at(out->_reply, 4)->as.real;
    out->accel_x = pilot_reply_at(out->_reply, 5)->as.real;
    out->accel_y = pilot_reply_at(out->_reply, 6)->as.real;
    out->accel_z = pilot_reply_at(out->_reply, 7)->as.real;
    return PILOT_OK;
}
void pilot_rtc_get_imu_data_clear(pilot_rtc_get_imu_data_result *out)
{
    if (out) { pilot_reply_free(out->_reply); memset(out, 0, sizeof(*out)); }
}
int pilot_rtc_get_device_param(pilot_client *client, pilot_rtc_get_device_param_result *out, pilot_error *error)
{
    if (!out) {
        if (error) { memset(error, 0, sizeof(*error)); error->code = PILOT_INVALID_ARGUMENT;
            strcpy(error->message, "Missing output argument"); }
        return PILOT_INVALID_ARGUMENT;
    }
    memset(out, 0, sizeof(*out));
    int rc = pilot_call(client, PILOT_METHOD_RTC_GET_DEVICE_PARAM,
                        NULL, 0, &out->_reply, error);
    if (rc != PILOT_OK) return rc;
    out->last_update_ms = pilot_reply_at(out->_reply, 0)->as.i64;
    out->has_imu = pilot_reply_at(out->_reply, 1)->as.boolean;
    out->gyro_x = pilot_reply_at(out->_reply, 2)->as.real;
    out->gyro_y = pilot_reply_at(out->_reply, 3)->as.real;
    out->gyro_z = pilot_reply_at(out->_reply, 4)->as.real;
    out->accel_x = pilot_reply_at(out->_reply, 5)->as.real;
    out->accel_y = pilot_reply_at(out->_reply, 6)->as.real;
    out->accel_z = pilot_reply_at(out->_reply, 7)->as.real;
    out->temperature = pilot_reply_at(out->_reply, 8)->as.real;
    out->memory_usage = pilot_reply_at(out->_reply, 9)->as.real;
    out->cpu_usage = pilot_reply_at(out->_reply, 10)->as.real;
    out->disk_usage = pilot_reply_at(out->_reply, 11)->as.real;
    out->battery_percent = pilot_reply_at(out->_reply, 12)->as.i32;
    out->voltage = pilot_reply_at(out->_reply, 13)->as.real;
    out->rssi_dbm = pilot_reply_at(out->_reply, 14)->as.i32;
    out->has_gps = pilot_reply_at(out->_reply, 15)->as.boolean;
    out->latitude = pilot_reply_at(out->_reply, 16)->as.real;
    out->longitude = pilot_reply_at(out->_reply, 17)->as.real;
    out->altitude = pilot_reply_at(out->_reply, 18)->as.real;
    out->gps_satellites = pilot_reply_at(out->_reply, 19)->as.i32;
    out->hdop = pilot_reply_at(out->_reply, 20)->as.real;
    return PILOT_OK;
}
void pilot_rtc_get_device_param_clear(pilot_rtc_get_device_param_result *out)
{
    if (out) { pilot_reply_free(out->_reply); memset(out, 0, sizeof(*out)); }
}
int pilot_rtc_get_magnetometer_data(pilot_client *client, pilot_rtc_get_magnetometer_data_result *out, pilot_error *error)
{
    if (!out) {
        if (error) { memset(error, 0, sizeof(*error)); error->code = PILOT_INVALID_ARGUMENT;
            strcpy(error->message, "Missing output argument"); }
        return PILOT_INVALID_ARGUMENT;
    }
    memset(out, 0, sizeof(*out));
    int rc = pilot_call(client, PILOT_METHOD_RTC_GET_MAGNETOMETER_DATA,
                        NULL, 0, &out->_reply, error);
    if (rc != PILOT_OK) return rc;
    out->last_update_ms = pilot_reply_at(out->_reply, 0)->as.i64;
    out->valid = pilot_reply_at(out->_reply, 1)->as.boolean;
    out->x_microtesla = pilot_reply_at(out->_reply, 2)->as.real;
    out->y_microtesla = pilot_reply_at(out->_reply, 3)->as.real;
    out->z_microtesla = pilot_reply_at(out->_reply, 4)->as.real;
    out->magnitude_microtesla = pilot_reply_at(out->_reply, 5)->as.real;
    out->sequence = pilot_reply_at(out->_reply, 6)->as.u64;
    return PILOT_OK;
}
void pilot_rtc_get_magnetometer_data_clear(pilot_rtc_get_magnetometer_data_result *out)
{
    if (out) { pilot_reply_free(out->_reply); memset(out, 0, sizeof(*out)); }
}
int pilot_rtc_get_cell_location(pilot_client *client, pilot_rtc_get_cell_location_result *out, pilot_error *error)
{
    if (!out) {
        if (error) { memset(error, 0, sizeof(*error)); error->code = PILOT_INVALID_ARGUMENT;
            strcpy(error->message, "Missing output argument"); }
        return PILOT_INVALID_ARGUMENT;
    }
    memset(out, 0, sizeof(*out));
    int rc = pilot_call(client, PILOT_METHOD_RTC_GET_CELL_LOCATION,
                        NULL, 0, &out->_reply, error);
    if (rc != PILOT_OK) return rc;
    out->state = pilot_reply_at(out->_reply, 0)->as.string;
    out->valid = pilot_reply_at(out->_reply, 1)->as.boolean;
    out->latitude = pilot_reply_at(out->_reply, 2)->as.real;
    out->longitude = pilot_reply_at(out->_reply, 3)->as.real;
    out->radius_m = pilot_reply_at(out->_reply, 4)->as.real;
    out->age_seconds = pilot_reply_at(out->_reply, 5)->as.u32;
    out->detail = pilot_reply_at(out->_reply, 6)->as.string;
    return PILOT_OK;
}
void pilot_rtc_get_cell_location_clear(pilot_rtc_get_cell_location_result *out)
{
    if (out) { pilot_reply_free(out->_reply); memset(out, 0, sizeof(*out)); }
}
int pilot_rtc_get_gps_status(pilot_client *client, pilot_rtc_get_gps_status_result *out, pilot_error *error)
{
    if (!out) {
        if (error) { memset(error, 0, sizeof(*error)); error->code = PILOT_INVALID_ARGUMENT;
            strcpy(error->message, "Missing output argument"); }
        return PILOT_INVALID_ARGUMENT;
    }
    memset(out, 0, sizeof(*out));
    int rc = pilot_call(client, PILOT_METHOD_RTC_GET_GPS_STATUS,
                        NULL, 0, &out->_reply, error);
    if (rc != PILOT_OK) return rc;
    out->status = pilot_reply_at(out->_reply, 0);
    return PILOT_OK;
}
void pilot_rtc_get_gps_status_clear(pilot_rtc_get_gps_status_result *out)
{
    if (out) { pilot_reply_free(out->_reply); memset(out, 0, sizeof(*out)); }
}
int pilot_rtc_get_channel_output_status(pilot_client *client, pilot_rtc_get_channel_output_status_result *out, pilot_error *error)
{
    if (!out) {
        if (error) { memset(error, 0, sizeof(*error)); error->code = PILOT_INVALID_ARGUMENT;
            strcpy(error->message, "Missing output argument"); }
        return PILOT_INVALID_ARGUMENT;
    }
    memset(out, 0, sizeof(*out));
    int rc = pilot_call(client, PILOT_METHOD_RTC_GET_CHANNEL_OUTPUT_STATUS,
                        NULL, 0, &out->_reply, error);
    if (rc != PILOT_OK) return rc;
    out->channels = pilot_reply_at(out->_reply, 0);
    out->debug_active = pilot_reply_at(out->_reply, 1)->as.boolean;
    out->last_remote_rx_ms = pilot_reply_at(out->_reply, 2)->as.i64;
    return PILOT_OK;
}
void pilot_rtc_get_channel_output_status_clear(pilot_rtc_get_channel_output_status_result *out)
{
    if (out) { pilot_reply_free(out->_reply); memset(out, 0, sizeof(*out)); }
}
int pilot_rtc_begin_channel_debug(pilot_client *client, pilot_rtc_begin_channel_debug_result *out, pilot_error *error)
{
    if (!out) {
        if (error) { memset(error, 0, sizeof(*error)); error->code = PILOT_INVALID_ARGUMENT;
            strcpy(error->message, "Missing output argument"); }
        return PILOT_INVALID_ARGUMENT;
    }
    memset(out, 0, sizeof(*out));
    int rc = pilot_call(client, PILOT_METHOD_RTC_BEGIN_CHANNEL_DEBUG,
                        NULL, 0, &out->_reply, error);
    if (rc != PILOT_OK) return rc;
    out->accepted = pilot_reply_at(out->_reply, 0)->as.boolean;
    out->reason = pilot_reply_at(out->_reply, 1)->as.string;
    return PILOT_OK;
}
void pilot_rtc_begin_channel_debug_clear(pilot_rtc_begin_channel_debug_result *out)
{
    if (out) { pilot_reply_free(out->_reply); memset(out, 0, sizeof(*out)); }
}
int pilot_rtc_set_channel_debug(pilot_client *client, uint32_t channel, uint32_t mode, int32_t value, bool enabled, pilot_rtc_set_channel_debug_result *out, pilot_error *error)
{
    if (!out) {
        if (error) { memset(error, 0, sizeof(*error)); error->code = PILOT_INVALID_ARGUMENT;
            strcpy(error->message, "Missing output argument"); }
        return PILOT_INVALID_ARGUMENT;
    }
    memset(out, 0, sizeof(*out));
    pilot_value args[4] = {0};
    args[0].type = 'u';
    args[0].as.u32 = channel;
    args[1].type = 'u';
    args[1].as.u32 = mode;
    args[2].type = 'i';
    args[2].as.i32 = value;
    args[3].type = 'b';
    args[3].as.boolean = enabled;
    int rc = pilot_call(client, PILOT_METHOD_RTC_SET_CHANNEL_DEBUG,
                        args, 4, &out->_reply, error);
    if (rc != PILOT_OK) return rc;
    out->accepted = pilot_reply_at(out->_reply, 0)->as.boolean;
    out->reason = pilot_reply_at(out->_reply, 1)->as.string;
    return PILOT_OK;
}
void pilot_rtc_set_channel_debug_clear(pilot_rtc_set_channel_debug_result *out)
{
    if (out) { pilot_reply_free(out->_reply); memset(out, 0, sizeof(*out)); }
}
int pilot_rtc_channel_debug_keep_alive(pilot_client *client, pilot_rtc_channel_debug_keep_alive_result *out, pilot_error *error)
{
    if (!out) {
        if (error) { memset(error, 0, sizeof(*error)); error->code = PILOT_INVALID_ARGUMENT;
            strcpy(error->message, "Missing output argument"); }
        return PILOT_INVALID_ARGUMENT;
    }
    memset(out, 0, sizeof(*out));
    int rc = pilot_call(client, PILOT_METHOD_RTC_CHANNEL_DEBUG_KEEP_ALIVE,
                        NULL, 0, &out->_reply, error);
    if (rc != PILOT_OK) return rc;
    out->active = pilot_reply_at(out->_reply, 0)->as.boolean;
    return PILOT_OK;
}
void pilot_rtc_channel_debug_keep_alive_clear(pilot_rtc_channel_debug_keep_alive_result *out)
{
    if (out) { pilot_reply_free(out->_reply); memset(out, 0, sizeof(*out)); }
}
int pilot_rtc_end_channel_debug(pilot_client *client, pilot_rtc_end_channel_debug_result *out, pilot_error *error)
{
    if (!out) {
        if (error) { memset(error, 0, sizeof(*error)); error->code = PILOT_INVALID_ARGUMENT;
            strcpy(error->message, "Missing output argument"); }
        return PILOT_INVALID_ARGUMENT;
    }
    memset(out, 0, sizeof(*out));
    int rc = pilot_call(client, PILOT_METHOD_RTC_END_CHANNEL_DEBUG,
                        NULL, 0, &out->_reply, error);
    if (rc != PILOT_OK) return rc;
    out->ended = pilot_reply_at(out->_reply, 0)->as.boolean;
    return PILOT_OK;
}
void pilot_rtc_end_channel_debug_clear(pilot_rtc_end_channel_debug_result *out)
{
    if (out) { pilot_reply_free(out->_reply); memset(out, 0, sizeof(*out)); }
}
int pilot_rtc_get_media_status(pilot_client *client, pilot_rtc_get_media_status_result *out, pilot_error *error)
{
    if (!out) {
        if (error) { memset(error, 0, sizeof(*error)); error->code = PILOT_INVALID_ARGUMENT;
            strcpy(error->message, "Missing output argument"); }
        return PILOT_INVALID_ARGUMENT;
    }
    memset(out, 0, sizeof(*out));
    int rc = pilot_call(client, PILOT_METHOD_RTC_GET_MEDIA_STATUS,
                        NULL, 0, &out->_reply, error);
    if (rc != PILOT_OK) return rc;
    out->status = pilot_reply_at(out->_reply, 0);
    return PILOT_OK;
}
void pilot_rtc_get_media_status_clear(pilot_rtc_get_media_status_result *out)
{
    if (out) { pilot_reply_free(out->_reply); memset(out, 0, sizeof(*out)); }
}
int pilot_rtc_get_audio_spectrum(pilot_client *client, pilot_rtc_get_audio_spectrum_result *out, pilot_error *error)
{
    if (!out) {
        if (error) { memset(error, 0, sizeof(*error)); error->code = PILOT_INVALID_ARGUMENT;
            strcpy(error->message, "Missing output argument"); }
        return PILOT_INVALID_ARGUMENT;
    }
    memset(out, 0, sizeof(*out));
    int rc = pilot_call(client, PILOT_METHOD_RTC_GET_AUDIO_SPECTRUM,
                        NULL, 0, &out->_reply, error);
    if (rc != PILOT_OK) return rc;
    out->available = pilot_reply_at(out->_reply, 0)->as.boolean;
    out->sample_rate = pilot_reply_at(out->_reply, 1)->as.u32;
    out->captured_ms = pilot_reply_at(out->_reply, 2)->as.i64;
    out->sequence = pilot_reply_at(out->_reply, 3)->as.u64;
    out->rms_dbfs = pilot_reply_at(out->_reply, 4)->as.real;
    out->peak_dbfs = pilot_reply_at(out->_reply, 5)->as.real;
    out->levels = pilot_reply_at(out->_reply, 6);
    return PILOT_OK;
}
void pilot_rtc_get_audio_spectrum_clear(pilot_rtc_get_audio_spectrum_result *out)
{
    if (out) { pilot_reply_free(out->_reply); memset(out, 0, sizeof(*out)); }
}
int pilot_rtc_get_audio_volume(pilot_client *client, pilot_rtc_get_audio_volume_result *out, pilot_error *error)
{
    if (!out) {
        if (error) { memset(error, 0, sizeof(*error)); error->code = PILOT_INVALID_ARGUMENT;
            strcpy(error->message, "Missing output argument"); }
        return PILOT_INVALID_ARGUMENT;
    }
    memset(out, 0, sizeof(*out));
    int rc = pilot_call(client, PILOT_METHOD_RTC_GET_AUDIO_VOLUME,
                        NULL, 0, &out->_reply, error);
    if (rc != PILOT_OK) return rc;
    out->available = pilot_reply_at(out->_reply, 0)->as.boolean;
    out->input_volume = pilot_reply_at(out->_reply, 1)->as.u32;
    out->output_volume = pilot_reply_at(out->_reply, 2)->as.u32;
    return PILOT_OK;
}
void pilot_rtc_get_audio_volume_clear(pilot_rtc_get_audio_volume_result *out)
{
    if (out) { pilot_reply_free(out->_reply); memset(out, 0, sizeof(*out)); }
}
int pilot_rtc_set_audio_volume(pilot_client *client, const char * target, uint32_t volume, pilot_rtc_set_audio_volume_result *out, pilot_error *error)
{
    if (!out) {
        if (error) { memset(error, 0, sizeof(*error)); error->code = PILOT_INVALID_ARGUMENT;
            strcpy(error->message, "Missing output argument"); }
        return PILOT_INVALID_ARGUMENT;
    }
    memset(out, 0, sizeof(*out));
    pilot_value args[2] = {0};
    args[0].type = 's';
    args[0].as.string = target;
    args[1].type = 'u';
    args[1].as.u32 = volume;
    int rc = pilot_call(client, PILOT_METHOD_RTC_SET_AUDIO_VOLUME,
                        args, 2, &out->_reply, error);
    if (rc != PILOT_OK) return rc;
    out->accepted = pilot_reply_at(out->_reply, 0)->as.boolean;
    out->actual_volume = pilot_reply_at(out->_reply, 1)->as.u32;
    out->reason = pilot_reply_at(out->_reply, 2)->as.string;
    return PILOT_OK;
}
void pilot_rtc_set_audio_volume_clear(pilot_rtc_set_audio_volume_result *out)
{
    if (out) { pilot_reply_free(out->_reply); memset(out, 0, sizeof(*out)); }
}
int pilot_rtc_capture_camera_preview(pilot_client *client, pilot_rtc_capture_camera_preview_result *out, pilot_error *error)
{
    if (!out) {
        if (error) { memset(error, 0, sizeof(*error)); error->code = PILOT_INVALID_ARGUMENT;
            strcpy(error->message, "Missing output argument"); }
        return PILOT_INVALID_ARGUMENT;
    }
    memset(out, 0, sizeof(*out));
    int rc = pilot_call(client, PILOT_METHOD_RTC_CAPTURE_CAMERA_PREVIEW,
                        NULL, 0, &out->_reply, error);
    if (rc != PILOT_OK) return rc;
    out->success = pilot_reply_at(out->_reply, 0)->as.boolean;
    out->width = pilot_reply_at(out->_reply, 1)->as.u32;
    out->height = pilot_reply_at(out->_reply, 2)->as.u32;
    out->stride_bytes = pilot_reply_at(out->_reply, 3)->as.u32;
    out->captured_ms = pilot_reply_at(out->_reply, 4)->as.i64;
    out->rgb565 = pilot_reply_at(out->_reply, 5);
    out->reason = pilot_reply_at(out->_reply, 6)->as.string;
    return PILOT_OK;
}
void pilot_rtc_capture_camera_preview_clear(pilot_rtc_capture_camera_preview_result *out)
{
    if (out) { pilot_reply_free(out->_reply); memset(out, 0, sizeof(*out)); }
}
int pilot_rtc_get_transport_stats(pilot_client *client, pilot_rtc_get_transport_stats_result *out, pilot_error *error)
{
    if (!out) {
        if (error) { memset(error, 0, sizeof(*error)); error->code = PILOT_INVALID_ARGUMENT;
            strcpy(error->message, "Missing output argument"); }
        return PILOT_INVALID_ARGUMENT;
    }
    memset(out, 0, sizeof(*out));
    int rc = pilot_call(client, PILOT_METHOD_RTC_GET_TRANSPORT_STATS,
                        NULL, 0, &out->_reply, error);
    if (rc != PILOT_OK) return rc;
    out->endpoints = pilot_reply_at(out->_reply, 0);
    return PILOT_OK;
}
void pilot_rtc_get_transport_stats_clear(pilot_rtc_get_transport_stats_result *out)
{
    if (out) { pilot_reply_free(out->_reply); memset(out, 0, sizeof(*out)); }
}
int pilot_rtc_get_diagnostic_stats(pilot_client *client, pilot_rtc_get_diagnostic_stats_result *out, pilot_error *error)
{
    if (!out) {
        if (error) { memset(error, 0, sizeof(*error)); error->code = PILOT_INVALID_ARGUMENT;
            strcpy(error->message, "Missing output argument"); }
        return PILOT_INVALID_ARGUMENT;
    }
    memset(out, 0, sizeof(*out));
    int rc = pilot_call(client, PILOT_METHOD_RTC_GET_DIAGNOSTIC_STATS,
                        NULL, 0, &out->_reply, error);
    if (rc != PILOT_OK) return rc;
    out->json = pilot_reply_at(out->_reply, 0)->as.string;
    return PILOT_OK;
}
void pilot_rtc_get_diagnostic_stats_clear(pilot_rtc_get_diagnostic_stats_result *out)
{
    if (out) { pilot_reply_free(out->_reply); memset(out, 0, sizeof(*out)); }
}
int pilot_rtc_get_network_diagnostics(pilot_client *client, pilot_rtc_get_network_diagnostics_result *out, pilot_error *error)
{
    if (!out) {
        if (error) { memset(error, 0, sizeof(*error)); error->code = PILOT_INVALID_ARGUMENT;
            strcpy(error->message, "Missing output argument"); }
        return PILOT_INVALID_ARGUMENT;
    }
    memset(out, 0, sizeof(*out));
    int rc = pilot_call(client, PILOT_METHOD_RTC_GET_NETWORK_DIAGNOSTICS,
                        NULL, 0, &out->_reply, error);
    if (rc != PILOT_OK) return rc;
    out->json = pilot_reply_at(out->_reply, 0)->as.string;
    return PILOT_OK;
}
void pilot_rtc_get_network_diagnostics_clear(pilot_rtc_get_network_diagnostics_result *out)
{
    if (out) { pilot_reply_free(out->_reply); memset(out, 0, sizeof(*out)); }
}
int pilot_rtc_request_reconnect(pilot_client *client, const char * endpoint, pilot_rtc_request_reconnect_result *out, pilot_error *error)
{
    if (!out) {
        if (error) { memset(error, 0, sizeof(*error)); error->code = PILOT_INVALID_ARGUMENT;
            strcpy(error->message, "Missing output argument"); }
        return PILOT_INVALID_ARGUMENT;
    }
    memset(out, 0, sizeof(*out));
    pilot_value args[1] = {0};
    args[0].type = 's';
    args[0].as.string = endpoint;
    int rc = pilot_call(client, PILOT_METHOD_RTC_REQUEST_RECONNECT,
                        args, 1, &out->_reply, error);
    if (rc != PILOT_OK) return rc;
    out->accepted = pilot_reply_at(out->_reply, 0)->as.boolean;
    out->reason = pilot_reply_at(out->_reply, 1)->as.string;
    return PILOT_OK;
}
void pilot_rtc_request_reconnect_clear(pilot_rtc_request_reconnect_result *out)
{
    if (out) { pilot_reply_free(out->_reply); memset(out, 0, sizeof(*out)); }
}
int pilot_selfcheck_get_report(pilot_client *client, pilot_selfcheck_get_report_result *out, pilot_error *error)
{
    if (!out) {
        if (error) { memset(error, 0, sizeof(*error)); error->code = PILOT_INVALID_ARGUMENT;
            strcpy(error->message, "Missing output argument"); }
        return PILOT_INVALID_ARGUMENT;
    }
    memset(out, 0, sizeof(*out));
    int rc = pilot_call(client, PILOT_METHOD_SELFCHECK_GET_REPORT,
                        NULL, 0, &out->_reply, error);
    if (rc != PILOT_OK) return rc;
    out->json = pilot_reply_at(out->_reply, 0)->as.string;
    return PILOT_OK;
}
void pilot_selfcheck_get_report_clear(pilot_selfcheck_get_report_result *out)
{
    if (out) { pilot_reply_free(out->_reply); memset(out, 0, sizeof(*out)); }
}
int pilot_selfcheck_run_now(pilot_client *client, pilot_selfcheck_run_now_result *out, pilot_error *error)
{
    if (!out) {
        if (error) { memset(error, 0, sizeof(*error)); error->code = PILOT_INVALID_ARGUMENT;
            strcpy(error->message, "Missing output argument"); }
        return PILOT_INVALID_ARGUMENT;
    }
    memset(out, 0, sizeof(*out));
    int rc = pilot_call(client, PILOT_METHOD_SELFCHECK_RUN_NOW,
                        NULL, 0, &out->_reply, error);
    if (rc != PILOT_OK) return rc;
    out->accepted = pilot_reply_at(out->_reply, 0)->as.boolean;
    out->reason = pilot_reply_at(out->_reply, 1)->as.string;
    return PILOT_OK;
}
void pilot_selfcheck_run_now_clear(pilot_selfcheck_run_now_result *out)
{
    if (out) { pilot_reply_free(out->_reply); memset(out, 0, sizeof(*out)); }
}
int pilot_selfcheck_get_network_recovery_policy(pilot_client *client, pilot_selfcheck_get_network_recovery_policy_result *out, pilot_error *error)
{
    if (!out) {
        if (error) { memset(error, 0, sizeof(*error)); error->code = PILOT_INVALID_ARGUMENT;
            strcpy(error->message, "Missing output argument"); }
        return PILOT_INVALID_ARGUMENT;
    }
    memset(out, 0, sizeof(*out));
    int rc = pilot_call(client, PILOT_METHOD_SELFCHECK_GET_NETWORK_RECOVERY_POLICY,
                        NULL, 0, &out->_reply, error);
    if (rc != PILOT_OK) return rc;
    out->ignored = pilot_reply_at(out->_reply, 0)->as.boolean;
    return PILOT_OK;
}
void pilot_selfcheck_get_network_recovery_policy_clear(pilot_selfcheck_get_network_recovery_policy_result *out)
{
    if (out) { pilot_reply_free(out->_reply); memset(out, 0, sizeof(*out)); }
}
int pilot_selfcheck_set_network_recovery_mode(pilot_client *client, const char * mode, pilot_selfcheck_set_network_recovery_mode_result *out, pilot_error *error)
{
    if (!out) {
        if (error) { memset(error, 0, sizeof(*error)); error->code = PILOT_INVALID_ARGUMENT;
            strcpy(error->message, "Missing output argument"); }
        return PILOT_INVALID_ARGUMENT;
    }
    memset(out, 0, sizeof(*out));
    pilot_value args[1] = {0};
    args[0].type = 's';
    args[0].as.string = mode;
    int rc = pilot_call(client, PILOT_METHOD_SELFCHECK_SET_NETWORK_RECOVERY_MODE,
                        args, 1, &out->_reply, error);
    if (rc != PILOT_OK) return rc;
    out->ignored = pilot_reply_at(out->_reply, 0)->as.boolean;
    return PILOT_OK;
}
void pilot_selfcheck_set_network_recovery_mode_clear(pilot_selfcheck_set_network_recovery_mode_result *out)
{
    if (out) { pilot_reply_free(out->_reply); memset(out, 0, sizeof(*out)); }
}
int pilot_fan_get_config(pilot_client *client, pilot_fan_get_config_result *out, pilot_error *error)
{
    if (!out) {
        if (error) { memset(error, 0, sizeof(*error)); error->code = PILOT_INVALID_ARGUMENT;
            strcpy(error->message, "Missing output argument"); }
        return PILOT_INVALID_ARGUMENT;
    }
    memset(out, 0, sizeof(*out));
    int rc = pilot_call(client, PILOT_METHOD_FAN_GET_CONFIG,
                        NULL, 0, &out->_reply, error);
    if (rc != PILOT_OK) return rc;
    out->json = pilot_reply_at(out->_reply, 0)->as.string;
    return PILOT_OK;
}
void pilot_fan_get_config_clear(pilot_fan_get_config_result *out)
{
    if (out) { pilot_reply_free(out->_reply); memset(out, 0, sizeof(*out)); }
}
int pilot_fan_set_config(pilot_client *client, const char * request, pilot_fan_set_config_result *out, pilot_error *error)
{
    if (!out) {
        if (error) { memset(error, 0, sizeof(*error)); error->code = PILOT_INVALID_ARGUMENT;
            strcpy(error->message, "Missing output argument"); }
        return PILOT_INVALID_ARGUMENT;
    }
    memset(out, 0, sizeof(*out));
    pilot_value args[1] = {0};
    args[0].type = 's';
    args[0].as.string = request;
    int rc = pilot_call(client, PILOT_METHOD_FAN_SET_CONFIG,
                        args, 1, &out->_reply, error);
    if (rc != PILOT_OK) return rc;
    out->json = pilot_reply_at(out->_reply, 0)->as.string;
    return PILOT_OK;
}
void pilot_fan_set_config_clear(pilot_fan_set_config_result *out)
{
    if (out) { pilot_reply_free(out->_reply); memset(out, 0, sizeof(*out)); }
}
